<a href="https://colab.research.google.com/github/youssefwael01200022488-cyber/real-stat-project/blob/main/Egyption_Real_Estate_2026_(final)_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **import libraries & upload data**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
re=pd.read_csv('/content/drive/MyDrive/propertyfinder.csv')

/tmp/ipykernel_443/1291415500.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  re=pd.read_csv('/content/drive/MyDrive/propertyfinder.csv')

## **adjust display options**

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.options.display.float_format = '{:,.2f}'.format

##**creating 2 dataframes**

In [ ]:
sell = re[re['category'] == 'buy'].copy()
rent = re[re['category'] == 'rent'].copy()
# sell=pd.read_csv('/content/drive/MyDrive/Sell.csv')
# rent=pd.read_csv('/content/drive/MyDrive/Rent.csv')

In [ ]:
columns_to_keep = [

    'property_type',
    'completion_status',
    'title',
    'price_egp',
    'city',
    'town',
    'district',
    'lat',
    'lon',
    'bedrooms',
    'bathrooms',
    'area_value',
    'furnished',
    'listing_level',
    #'is_premium',
    #'is_featured',
    'listed_date',
    'payment_method',
    'description',
    'agent_id',
    'broker_id',
]
sell=sell[columns_to_keep]
rent=rent[columns_to_keep]

In [ ]:
rent #19910 rows

,property_type,completion_status,title,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,listed_date,payment_method,description,agent_id,broker_id
19803,Apartment,NaN,First use semi furnished 2BR in El Patio Oro,"35,000.00",Cairo,New Cairo City,The 5th Settlement,30.03,31.59,2,2,128.00,PARTLY,premium,2026-03-04T21:13:08Z,NaN,Apartment with kitchen and air conditioning fo...,"55,901.00","5,389.00"
19804,Apartment,NaN,"Unfurnished apartment for rent with kitchen, a...","50,000.00",Cairo,New Cairo City,El Banafseg,30.05,31.47,3,3,300.00,NO,premium,2026-03-04T12:47:53Z,NaN,E14755 Unfurnished apartment for rent with kit...,"66,449.00","2,520.00"
19805,Apartment,NaN,Furnished apartment for rent in Al Yasmin 2 Vi...,"45,000.00",Cairo,New Cairo City,El Yasmeen,30.05,31.45,3,3,210.00,YES,premium,2026-03-04T11:12:17Z,NaN,E14748 Furnished apartment for rent in Al Yasm...,"66,449.00","2,520.00"
19806,Apartment,NaN,Unfurnished apartment for rent with air condit...,"25,000.00",Cairo,New Cairo City,Abou El Houl,29.98,31.47,2,2,150.00,NO,premium,2026-03-04T10:58:28Z,NaN,E14745 Unfurnished apartment for rent with air...,"50,635.00","2,520.00"
19807,Apartment,NaN,Furnished apartment for rent behind Mirage Cit...,"40,000.00",Cairo,New Cairo City,The 1st Settlement,30.05,31.44,2,2,130.00,YES,premium,2026-03-04T09:19:33Z,NaN,E12494B Furnished apartment for rent behind Mi...,"44,158.00","2,520.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,Apartment,NaN,"Furnished apartment for rent in Al Rehab, 250M","55,000.00",Cairo,New Cairo City,Al Rehab,30.06,31.51,3,3,250.00,YES,standard,2026-02-07T16:33:32Z,NaN,Furnished apartment for rent in Al Rehab Phase...,"68,162.00","4,456.00"
39709,Apartment,NaN,FULLY FURNISHED apartment for RENT 3 Bedroom,"45,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.09,3,3,180.00,YES,standard,2026-02-07T16:32:23Z,NaN,"AVAILABLE MID AUGUST, 2025 An Elegant 3 Bedroo...","23,636.00",430.00
39710,Townhouse,NaN,Furnished villa for rent in Town 5 rooms near New,"120,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.04,5,5,320.00,YES,standard,2026-02-07T16:31:32Z,NaN,Furnished villa for rent at a special price To...,"16,061.00","4,679.00"
39711,Apartment,NaN,For Rent – Premium 196m² Fully Finished Apartment,"50,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.06,2,2,196.00,NO,standard,2026-02-07T16:29:24Z,NaN,For Rent – Premium 196m² Fully Finished Apartm...,"60,109.00",430.00
39712,Apartment,NaN,If you're looking hotel units contact us now,"75,000.00",Cairo,New Cairo City,The 5th Settlement,30.02,31.55,2,2,144.00,YES,standard,2026-02-07T16:26:50Z,NaN,Unit Description: Location: Villette Compound ...,"56,917.00","5,307.00"

## **data understanding**

In [ ]:
re.shape

(39713, 53)

In [ ]:
re.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39713 entries, 0 to 39712
Data columns (total 53 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           39712 non-null  object
 1   internal_id          39712 non-null  float64
 2   category             39713 non-null  object
 3   listing_type         39713 non-null  object
 4   detail_url           39712 non-null  object
 5   property_type        39712 non-null  object
 6   offering_type        39712 non-null  object
 7   completion_status    19763 non-null  object
 8   title                39712 non-null  object
 9   price_egp            39712 non-null  float64
 10  price_period         39712 non-null  object
 11  price_currency       39713 non-null  object
 12  location_full        39712 non-null  object
 13  city                 39712 non-null  object
 14  town                 39712 non-null  object
 15  district             39366 non-null  object
 16  subdistrict          32954 non-null  object
 17  lat                  39712 non-null  float64
 18  lon                  39712 non-null  float64
 19  bedrooms             39678 non-null  object
 20  bathrooms            39683 non-null  object
 21  area_value           39712 non-null  float64
 22  area_unit            39713 non-null  object
 23  furnished            31328 non-null  object
 24  listing_level        39712 non-null  object
 25  is_premium           39713 non-null  bool
 26  is_verified          39713 non-null  bool
 27  is_featured          39713 non-null  bool
 28  is_new_construction  39713 non-null  bool
 29  is_direct_from_dev   39713 non-null  bool
 30  is_exclusive         39713 non-null  bool
 31  listed_date          39712 non-null  object
 32  images_count         39713 non-null  int64
 33  has_view_360         39713 non-null  bool
 34  video_url            202 non-null    object
 35  reference            39712 non-null  object
 36  rera                 0 non-null      float64
 37  description          39712 non-null  object
 38  amenities            39680 non-null  object
 39  payment_method       19939 non-null  object
 40  agent_id             39712 non-null  float64
 41  agent_name           39705 non-null  object
 42  agent_email          39712 non-null  object
 43  agent_is_super       39713 non-null  bool
 44  agent_languages      9172 non-null   object
 45  broker_id            39712 non-null  float64
 46  broker_name          39712 non-null  object
 47  broker_email         39510 non-null  object
 48  broker_phone         39510 non-null  float64
 49  contact_phone        39712 non-null  float64
 50  contact_whatsapp     39712 non-null  float64
 51  contact_email        39712 non-null  object
 52  scraped_at           39713 non-null  object
dtypes: bool(8), float64(11), int64(1), object(33)
memory usage: 13.9+ MB

In [ ]:
re.head()

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,price_period,price_currency,location_full,city,town,district,subdistrict,lat,lon,bedrooms,bathrooms,area_value,area_unit,furnished,listing_level,is_premium,is_verified,is_featured,is_new_construction,is_direct_from_dev,is_exclusive,listed_date,images_count,has_view_360,video_url,reference,rera,description,amenities,payment_method,agent_id,agent_name,agent_email,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,"56,009,081.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,"24,500,000.00",sell,EGP,"The Lakeview Boutique Villas, 5th Settlement C...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.04,31.53,3,6,445.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T19:15:06Z,6,False,NaN,F7QB31CGWE509V2W7DF2GARB2C,NaN,Garden Villa for Sale – Featured in Lake View ...,Balcony | Built in Wardrobes | Covered Parking...,cash,"58,866.00",pierre osama,pierre.Osama@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,201,801,443.00","20,221,257,340.00",pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,"56,247,925.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,"5,145,000.00",sell,EGP,"Village West, Sheikh Zayed Compounds, Sheikh Z...",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Village West,30.05,31.02,2,2,123.00,sqm,PARTLY,premium,True,False,False,False,False,False,2026-03-04T11:24:23Z,10,False,NaN,rb304,NaN,For Sale: Finished Apartment with ACs in Villa...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"67,166.00",Rana Bahaa ElDeen,ranoushamer901@gmail.com,False,NaN,492.00,Abrag Real Estate,snawara71@gmail.com,"201,001,188,088.00","201,007,169,666.00","20,221,257,340.00",ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,"56,253,883.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,"10,800,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,4,4,250.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-04T14:03:51Z,13,False,NaN,250pncash,NaN,Palm Hills New Cairo Apartment BUA: 250sqm 4 B...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,158.00",Ashraf Shaaban,ashrafsobhy99@hotmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,090,963,241.00","20,221,257,340.00",ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,"56,250,852.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,"10,500,000.00",sell,EGP,"Lake View Residence, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.03,31.54,2,2,136.00,sqm,YES,premium,True,False,False,False,False,False,2026-03-04T12:38:11Z,11,False,NaN,PPH0852SAB266X6GSVATJP4F0M,NaN,Lake View Residence 136 sqm Fully Finished Ren...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"63,401.00",ebrahim hossam,ebrahim.hossam@spade-consultancy.com,False,NaN,"5,758.00",Spade consultancy,mohmedg.sedik@gmail.com,"1,001,436,511.00","201,070,115,211.00","20,221,257,340.00",ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,"55,995,764.00",buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,"19,500,000.00",sell,EGP,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,30.01,31.58,4,4,255.00,sqm,NaN,premium,True,False,False,False,False,False,2026-03-03T09:45:41Z,17,False,NaN,VillTyM,NaN,Palm Hills New Cairo Type M BUA: 255sqm LAND: ...,Balcony | Built in Wardrobes | Central A/C | C...,cash,"47,158.00",Ashraf Shaaban,ashrafsobhy99@hotmail.com,False,English | Arabic,"5,279.00",Premises,mahmouddessam@hotmail.com,"201,005,133,389.00","201,090,963,241.00","20,221,257,340.00",ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007

In [ ]:
re.isnull().sum().sort_values(ascending=False)

rera                   39713
video_url              39511
agent_languages        30541
completion_status      19950
payment_method         19774
furnished               8385
subdistrict             6759
district                 347
broker_email             203
broker_phone             203
bedrooms                  35
amenities                 33
bathrooms                 30
agent_name                 8
city                       1
detail_url                 1
location_full              1
listing_id                 1
property_type              1
offering_type              1
internal_id                1
contact_email              1
agent_email                1
broker_name                1
lat                        1
price_egp                  1
price_period               1
town                       1
lon                        1
title                      1
agent_id                   1
description                1
area_value                 1
reference                  1
listed_date                1
listing_level              1
contact_phone              1
contact_whatsapp           1
broker_id                  1
category                   0
listing_type               0
price_currency             0
has_view_360               0
is_featured                0
is_new_construction        0
area_unit                  0
is_direct_from_dev         0
is_exclusive               0
images_count               0
is_premium                 0
is_verified                0
agent_is_super             0
scraped_at                 0
dtype: int64

In [ ]:
re.describe()

,internal_id,price_egp,lat,lon,area_value,images_count,rera,agent_id,broker_id,broker_phone,contact_phone,contact_whatsapp
count,"39,712.00","39,712.00","39,712.00","39,712.00","39,712.00","39,713.00",0.00,"39,712.00","39,712.00","39,510.00","39,712.00","39,712.00"
mean,"45,379,476.59","7,988,803.42",29.98,31.32,218.48,12.28,NaN,"53,288.36","4,144.89","151,703,584,082.74","303,189,659,577,194.75","63,187,517,500.30"
std,"18,804,978.55","24,492,789.87",0.60,0.86,781.82,4.82,NaN,"17,909.36","10,005.16","86,252,580,080.09","60,379,162,250,925,584.00","76,980,188,309.43"
min,"2,908,155.00","1,300.00",25.07,25.48,1.00,0.00,NaN,"5,500.00",55.00,"1,000,009,081.00","201,000,001,398.00","20,221,257,340.00"
25%,"52,454,285.00","65,000.00",30.00,31.02,130.00,10.00,NaN,"42,365.00","1,614.00","201,000,137,017.00","201,032,992,760.00","20,221,257,340.00"
50%,"54,760,999.50","600,000.00",30.03,31.50,175.00,11.00,NaN,"57,459.00","4,208.00","201,026,694,777.00","201,102,191,494.00","20,221,257,340.00"
75%,"55,758,653.75","9,113,125.00",30.06,31.55,245.00,14.00,NaN,"68,818.00","5,657.00","201,117,033,304.00","201,145,564,556.00","20,221,257,340.00"
max,"56,493,417.00","1,000,000,000.00",31.50,34.90,"96,600.00",30.00,NaN,"73,845.00","179,957.00","201,558,194,855.00","12,032,281,120,109,799,424.00","201,559,777,173.00"

In [ ]:
re.describe(include='object')

,listing_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_period,price_currency,location_full,city,town,district,subdistrict,bedrooms,bathrooms,area_unit,furnished,listing_level,listed_date,video_url,reference,description,amenities,payment_method,agent_name,agent_email,agent_languages,broker_name,broker_email,contact_email,scraped_at
count,39712,39713,39713,39712,39712,39712,19763,39712,39712,39713,39712,39712,39712,39366,32954,39678,39683,39713,31328,39712,39712,202,39712,39712,39680,19939,39705,39712,9172,39712,39510,39712,39713
unique,39712,2,2,39712,19,2,4,32700,2,1,1959,12,67,519,1134,9,9,1,3,3,36255,154,39645,35312,17995,3,2659,2732,30,776,770,2732,4736
top,8GRB2Q98JVYH9K1KCDS9B60228,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,completed,Hotel apartment for rent inAlRehab fully furni...,monthly,EGP,"Mivida, 5th Settlement Compounds, The 5th Sett...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds,3,3,sqm,YES,standard,2026-02-09T11:27:08Z,https://www.youtube.com/watch?v=ouXREODabm0,7,We offer all real estate services in some of t...,Balcony | Built in Wardrobes | Central A/C | C...,cash,FORTUNE REALTY,fourtunerealityeg@gmail.com,English | Arabic,Egypt Best Properties,info@egyptbestproperties.com,fourtunerealityeg@gmail.com,2026-03-05T00:23:48.917099
freq,1,19910,39712,1,25211,19910,10135,215,19910,39713,2433,25865,19738,13082,11671,18189,14168,39713,12719,31249,13,7,5,67,1467,12806,576,576,6679,1490,1490,576,25

In [ ]:
re[['internal_id', 'agent_id', 'broker_id',
    'broker_phone', 'contact_phone', 'contact_whatsapp']].nunique()

internal_id         39712
agent_id             2773
broker_id             776
broker_phone          769
contact_phone        2483
contact_whatsapp      422
dtype: int64

In [ ]:
re['property_type'].unique()

array(['Duplex', 'Apartment', 'Villa', nan, 'Penthouse', 'Twin House',
       'Townhouse', 'Chalet', 'iVilla', 'Hotel Apartment',
       'Whole Building', 'Half Floor', 'Land', 'Bulk Sale Unit', 'Cabin',
       'Roof', 'Palace', 'Full Floor', 'Bulk Rent Unit', 'Bungalow'],
      dtype=object)

In [ ]:
re['completion_status'].unique()

# completed:  (Resale)عقار مكتمل البناء ومباع عن طريق إعادة البيع

# off_plan:  (Resale) عقار قيد الإنشاء أو تحت التخطيط

# completed_primary:  (Primary)عقار مكتمل الجاهزية ومباع مباشرة من الشركة /المطور

# off_plan_primary: عقار تحت الإنشاء ومباع مباشرة من المطور مع خطط سداد.

array(['completed', 'off_plan', nan, 'completed_primary',
       'off_plan_primary'], dtype=object)

### extreme values invastigation

In [ ]:
# has been dealt with
sell.nsmallest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district
497,"113,116.00",Apartment,155.00,3,3,Giza,6 October City,6 October Compounds
85,"130,000.00",Duplex,233.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
87,"130,000.00",Apartment,233.00,3,3,Giza,Sheikh Zayed City,Ivoire
2139,"155,220.00",Apartment,200.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
13056,"200,000.00",Chalet,1.00,2,2,Suez,Al Ain Al Sokhna,IL Monte Galala
223,"300,000.00",Chalet,120.00,2,2,Suez,Al Ain Al Sokhna,IL Monte Galala
11781,"300,000.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement
11836,"300,000.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement
2792,"303,000.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement
797,"325,000.00",Chalet,1.00,1,1,Suez,Al Ain Al Sokhna,IL Monte Galala
476,"340,000.00",Apartment,106.00,2,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
1341,"345,500.00",Apartment,20.00,3,3,Cairo,New Cairo City,The 5th Settlement
1193,"350,000.00",Apartment,20.00,2,2,Cairo,Mostakbal City - Future City,Mostakbal City Compounds
12782,"350,000.00",Chalet,20.00,studio,1,Suez,Al Ain Al Sokhna,IL Monte Galala
1449,"356,000.00",Apartment,20.00,3,2,Cairo,New Cairo City,The 5th Settlement
1470,"356,000.00",Apartment,20.00,3,2,Cairo,New Cairo City,The 5th Settlement
1211,"356,100.00",Apartment,20.00,3,2,Cairo,New Cairo City,The 5th Settlement
9316,"360,000.00",Apartment,20.00,2,2,Cairo,New Capital City,New Capital Compounds
19503,"370,000.00",Apartment,20.00,1,1,Cairo,Mostakbal City - Future City,Mostakbal City Compounds
19512,"370,000.00",Apartment,20.00,1,1,Cairo,Mostakbal City - Future City,Mostakbal City Compounds

In [ ]:
# no dealing requiered
sell.nlargest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district
3798,"1,000,000,000.00",Villa,238.00,3,7,North Coast,Ras Al Hekma,Jefaira
6177,"988,888,888.00",Villa,"1,352.00",7,7+,Cairo,Zamalek,Mohamed Mazhar St.
6179,"958,000,000.00",Villa,"1,255.00",6,6,Cairo,Zamalek,El Gezirah St.
10350,"940,000,000.00",Land,"96,600.00",NaN,NaN,Giza,6 October City,Al Wahat Road
10358,"940,000,000.00",Land,"96,600.00",NaN,NaN,Giza,6 October City,Al Wahat Road
14187,"912,000,000.00",Whole Building,"4,000.00",7+,7+,Cairo,New Cairo City,The 5th Settlement
14188,"912,000,000.00",Whole Building,"4,000.00",7+,7+,Cairo,New Cairo City,The 5th Settlement
11135,"900,000,000.00",Palace,"4,800.00",7+,7+,Giza,6 October City,Cairo Alexandria Desert Road
6256,"850,000,000.00",Land,"1,100.00",NaN,NaN,Cairo,Garden City,Nile Corniche St.
11167,"844,000,000.00",Palace,"4,810.00",7+,7+,Giza,6 October City,Cairo Alexandria Desert Road
11206,"770,400,000.00",Land,"38,520.00",NaN,NaN,Giza,Sheikh Zayed City,Riviera City
5249,"750,111,111.00",Villa,"1,647.00",7+,7+,Cairo,Garden City,Ahmed Basha St.
6395,"750,000,000.00",Villa,"1,801.00",5,6,Cairo,New Cairo City,El Katameya
9305,"750,000,000.00",Villa,"1,800.00",5,6,Cairo,New Cairo City,El Katameya
14208,"682,125,000.00",Apartment,159.00,3,3,Cairo,New Cairo City,The 5th Settlement
14185,"670,000,000.00",Whole Building,"4,000.00",7+,7+,Cairo,New Cairo City,The 5th Settlement
3796,"650,000,000.00",Townhouse,138.00,3,4,North Coast,Ras Al Hekma,Jefaira
12387,"442,000,000.00",Villa,552.00,5,5,North Coast,Sidi Abdel Rahman,Marassi
12389,"442,000,000.00",Villa,552.00,5,5,North Coast,Sidi Abdel Rahman,Marassi
8762,"427,500,000.00",Villa,"1,000.00",5,7,Cairo,New Cairo City,El Katameya

In [ ]:
# no dealing requiered
sell.nlargest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district
10350,"96,600.00","940,000,000.00",Land,NaN,NaN,Giza,6 October City,Al Wahat Road
10358,"96,600.00","940,000,000.00",Land,NaN,NaN,Giza,6 October City,Al Wahat Road
10500,"42,000.00","400,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt
11206,"38,520.00","770,400,000.00",Land,NaN,NaN,Giza,Sheikh Zayed City,Riviera City
10419,"21,000.00","140,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt
10482,"21,000.00","140,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt
17634,"14,000.00","120,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt
9842,"12,000.00","350,000,000.00",Land,NaN,NaN,Cairo,New Cairo City,The 5th Settlement
5609,"10,600.00","265,000,000.00",Land,NaN,NaN,North Coast,Al Alamein,NaN
6021,"5,600.00","350,000,000.00",Hotel Apartment,7+,7+,Cairo,Downtown,Qasr El Nil
11167,"4,810.00","844,000,000.00",Palace,7+,7+,Giza,6 October City,Cairo Alexandria Desert Road
11135,"4,800.00","900,000,000.00",Palace,7+,7+,Giza,6 October City,Cairo Alexandria Desert Road
7745,"4,000.00","90,000,000.00",Land,NaN,NaN,Giza,6 October City,Green Belt
14185,"4,000.00","670,000,000.00",Whole Building,7+,7+,Cairo,New Cairo City,The 5th Settlement
14187,"4,000.00","912,000,000.00",Whole Building,7+,7+,Cairo,New Cairo City,The 5th Settlement
14188,"4,000.00","912,000,000.00",Whole Building,7+,7+,Cairo,New Cairo City,The 5th Settlement
12961,"3,500.00","250,000,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya
16002,"3,000.00","170,000,000.00",Villa,7+,7+,Cairo,New Cairo City,Al Rehab
6198,"2,900.00","93,000,000.00",Whole Building,7+,7+,Cairo,Downtown,NaN
4321,"2,633.00","53,000,000.00",Whole Building,3,7+,Cairo,Garden City,Garden City St.

In [ ]:
# has been dealt with
sell.nsmallest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district
80,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,6th District
153,1.00,"582,800.00",Hotel Apartment,2,2,Cairo,Shorouk City,El Shorouk Compounds
154,1.00,"709,700.00",Hotel Apartment,3,3,Cairo,Shorouk City,El Shorouk Compounds
797,1.00,"325,000.00",Chalet,1,1,Suez,Al Ain Al Sokhna,IL Monte Galala
7819,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
7843,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
7853,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
7864,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
7886,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,17th District
7914,1.00,"610,000.00",Villa,4,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
9201,1.00,"673,000.00",Hotel Apartment,1,1,Cairo,El Nozha,Sheraton Al Matar
9277,1.00,"497,209.00",Penthouse,1,2,Cairo,New Cairo City,The 5th Settlement
9449,1.00,"1,350,000.00",Chalet,3,3,Suez,Al Ain Al Sokhna,La Vista
9582,1.00,"4,100,000.00",Duplex,2,2,Cairo,New Cairo City,The 5th Settlement
12219,1.00,"4,000,000.00",Chalet,2,2,North Coast,Ras Al Hekma,Jefaira
12222,1.00,"5,660,000.00",Villa,5,5,Giza,6 October City,Cairo Alexandria Desert Road
12712,1.00,"5,400,000.00",Twin House,4,4,Cairo,Shorouk City,El Shorouk Compounds
13056,1.00,"200,000.00",Chalet,2,2,Suez,Al Ain Al Sokhna,IL Monte Galala
15468,1.00,"4,300,000.00",Penthouse,3,3,Cairo,New Cairo City,The 5th Settlement
16327,1.00,"5,800,000.00",Villa,5,5,Giza,6 October City,Cairo Alexandria Desert Road

In [ ]:
# has been dealt with
rent.nlargest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district
35356,"305,000,000.00",Villa,"1,150.00",4,4,Cairo,New Cairo City,The 5th Settlement
33739,"185,000,000.00",Townhouse,260.00,4,5,Cairo,New Cairo City,South Investors Area
20818,"160,000,000.00",Villa,357.00,5,5,Giza,6 October City,Cairo Alexandria Desert Road
27617,"130,000,000.00",Townhouse,320.00,3,4,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
21275,"125,000,000.00",Townhouse,380.00,3,4,Giza,6 October City,Al Wahat Road
26542,"90,000,000.00",Townhouse,250.00,4,4,Cairo,New Cairo City,Ext North Inves Area
37982,"70,000,000.00",Apartment,122.00,2,2,Cairo,New Cairo City,The 5th Settlement
28881,"60,000,000.00",Palace,"2,500.00",7,7+,North Coast,Sidi Abdel Rahman,Marassi
32815,"37,000,000.00",Villa,360.00,4,4,Cairo,New Cairo City,The 5th Settlement
37865,"28,113,558.00",Villa,800.00,4,5,Cairo,New Cairo City,Hyde Park
20424,"25,000,000.00",Twin House,279.00,4,4,Giza,Sheikh Zayed City,6th District
32827,"24,600,000.00",Townhouse,257.00,4,4,Cairo,New Cairo City,The 5th Settlement
37860,"21,085,812.00",Twin House,290.00,5,5,Cairo,New Cairo City,Hyde Park
26706,"18,620,000.00",Penthouse,235.00,3,3,Cairo,New Cairo City,South Investors Area
36061,"17,000,000.00",Apartment,205.00,3,3,Cairo,New Cairo City,The 5th Settlement
31626,"16,000,000.00",Apartment,211.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
23113,"15,890,000.00",Apartment,162.00,3,3,Cairo,New Cairo City,The 5th Settlement
23211,"15,000,000.00",Duplex,245.00,3,3,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
38152,"15,000,000.00",Villa,400.00,3,3,Cairo,New Cairo City,The 5th Settlement
27626,"14,500,000.00",Apartment,149.00,2,3,Cairo,New Cairo City,The 5th Settlement

In [ ]:
# has been dealt with
rent.nsmallest(20, 'price_egp')[
    ['price_egp', 'property_type', 'area_value',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,price_egp,property_type,area_value,bedrooms,bathrooms,city,town,district
20565,"1,300.00",Apartment,157.00,2,3,Cairo,New Cairo City,The 5th Settlement
20587,"1,400.00",Villa,180.00,3,3,Cairo,New Cairo City,The 5th Settlement
21056,"1,400.00",Apartment,210.00,3,3,Cairo,New Cairo City,The 5th Settlement
20586,"1,700.00",iVilla,278.00,4,3,Cairo,New Cairo City,The 5th Settlement
21646,"1,750.00",Apartment,170.00,2,4,Cairo,New Cairo City,North Investors Area
20563,"1,800.00",Apartment,268.00,3,3,Cairo,New Cairo City,The 5th Settlement
20901,"2,000.00",Villa,355.00,5,5,Cairo,New Cairo City,The 5th Settlement
20445,"2,200.00",Apartment,400.00,3,3,Cairo,New Cairo City,El Katameya
20561,"2,200.00",Apartment,190.00,3,3,Cairo,New Cairo City,The 5th Settlement
20719,"3,000.00",Apartment,70.00,3,1,Qalyubia,Shobra Al Khaimah,NaN
21112,"3,000.00",Apartment,96.00,2,2,Cairo,Madinaty,Privado
20451,"4,444.00",Apartment,70.00,1,1,Cairo,Madinaty,NaN
20682,"4,500.00",Apartment,80.00,2,1,Giza,6 October City,Al Wahat Road
20714,"4,800.00",Apartment,20.00,studio,1,Giza,6 October City,Al Hosary
20441,"5,000.00",Apartment,90.00,2,1,Cairo,Nasr City,1st Zone
20442,"5,000.00",Apartment,100.00,2,1,Cairo,Nasr City,6th Zone
20631,"5,500.00",Apartment,150.00,3,3,Cairo,Nasr City,6th Zone
21922,"5,600.00",Apartment,35.00,studio,1,Giza,6 October City,3rd District
21707,"6,000.00",Apartment,60.00,1,1,Cairo,Heliopolis - Masr El Gedida,Roxy
21857,"6,000.00",Apartment,200.00,3,2,Cairo,Nasr City,Masaken Al Mohandesin

In [ ]:
rent.nlargest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district
21043,"3,500.00","610,000.00",Villa,6,7+,Giza,Sheikh Zayed City,16th District
25866,"3,000.00","625,000.00",Villa,6,7+,Giza,Sheikh Zayed City,16th District
27972,"3,000.00","500,000.00",Villa,7,7+,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
27105,"2,700.00","386,000.00",Villa,5,7,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
26946,"2,500.00","700,000.00",Villa,7,7,Cairo,New Cairo City,El Katameya
28881,"2,500.00","60,000,000.00",Palace,7,7+,North Coast,Sidi Abdel Rahman,Marassi
29154,"2,500.00","900,000.00",Villa,7,7+,Cairo,New Cairo City,El Katameya
29172,"2,500.00","637,000.00",Villa,7+,7+,Cairo,New Cairo City,The 5th Settlement
29742,"2,400.00","260,000.00",Villa,6,7+,Giza,Sheikh Zayed City,4th District
36794,"2,400.00","275,000.00",Villa,7,7+,Giza,Sheikh Zayed City,4th District
20242,"2,000.00","576,000.00",Villa,7,7+,Cairo,New Cairo City,El Katameya
29149,"2,000.00","650,000.00",Villa,4,5,Cairo,New Cairo City,The 5th Settlement
29164,"2,000.00","800,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya
29179,"2,000.00","833,000.00",Villa,6,7,Cairo,New Cairo City,El Katameya
33545,"2,000.00","750,000.00",Palace,7+,7+,Cairo,New Cairo City,The 5th Settlement
36535,"2,000.00","350,000.00",Villa,7+,7+,Cairo,New Cairo City,El Katameya
30942,"1,920.00","850,000.00",Whole Building,7+,7+,Giza,Mohandessin,Ahmed Orabi St.
29181,"1,800.00","650,000.00",Villa,6,7,Cairo,New Cairo City,El Katameya
31130,"1,800.00","410,000.00",Villa,7,7+,Giza,6 October City,Cairo Alexandria Desert Road
20131,"1,700.00","500,000.00",Villa,7+,6,Cairo,New Cairo City,El Katameya

In [ ]:
# has been dealt with
rent.nsmallest(20, 'area_value')[
    ['area_value', 'price_egp', 'property_type',
     'bedrooms', 'bathrooms', 'city', 'town', 'district']
]

,area_value,price_egp,property_type,bedrooms,bathrooms,city,town,district
27032,1.00,"85,000.00",iVilla,3,3,Cairo,New Cairo City,The 5th Settlement
32342,6.00,"170,000.00",Villa,4,3,Cairo,New Cairo City,Hyde Park
20714,20.00,"4,800.00",Apartment,studio,1,Giza,6 October City,Al Hosary
30542,20.00,"18,000.00",Apartment,1,1,Cairo,New Cairo City,El Lotus
36330,20.00,"45,000.00",Apartment,studio,1,Cairo,New Cairo City,El Lotus
24554,25.00,"28,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,17th District
24563,25.00,"25,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,17th District
25371,25.00,"30,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
26503,25.00,"15,000.00",Apartment,1,1,Cairo,New Cairo City,El Lotus
29803,25.00,"25,999.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
30599,25.00,"20,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,6th District
30604,25.00,"20,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
31096,25.00,"25,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
34598,25.00,"20,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
35573,25.00,"31,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,17th District
36924,25.00,"25,000.00",Apartment,studio,1,Cairo,New Cairo City,El Lotus
37161,25.00,"25,000.00",Apartment,studio,1,Cairo,New Cairo City,El Lotus
39124,25.00,"25,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
31878,26.00,"17,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds
31882,26.00,"22,000.00",Apartment,studio,1,Giza,Sheikh Zayed City,Sheikh Zayed Compounds

## **bedrooms & bathrooms breaking down**

In [ ]:
re['bedrooms'].value_counts(dropna=False)

bedrooms
3         18189
2          9418
4          6121
5          2128
1          1616
studio     1125
6           670
7           227
7+          184
NaN          35
Name: count, dtype: int64

In [ ]:
sell[['bedrooms','bathrooms']].isna().sum()

bedrooms     32
bathrooms    30
dtype: int64

In [ ]:
rent[['bedrooms','bathrooms']].isna().sum()

bedrooms     3
bathrooms    0
dtype: int64

In [ ]:
sell[sell['bedrooms'].isna() | sell['bathrooms'].isna()]

,property_type,completion_status,title,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,listed_date,payment_method,description,agent_id,broker_id
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3219,Land,NaN,علي طريق السويس مباشر_ بحري _شمال الرحاب _التجمع,"11,300,000.00",Cairo,New Cairo City,The 5th Settlement,30.06,31.55,NaN,NaN,450.00,NaN,premium,2026-02-15T12:12:56Z,cash,علي طريق السويس مباشر_ بحري _شمال الرحاب _التج...,"47,176.00","5,253.00"
3259,Land,NaN,ارض تجاري فرصة للمطورين وشركات الاستثمار العقاري,"67,500,000.00",Giza,6 October City,1st District,29.96,30.96,NaN,NaN,"1,500.00",NaN,premium,2026-01-22T17:24:53Z,cash,فرصة للمطورين وشركات الاستثمار العقاري ارض بمس...,"36,502.00","4,226.00"
3694,Bulk Sale Unit,completed,Investment Building for Sale 1600 sqm in a Prime,"55,000,000.00",Giza,6 October City,Al Hosary,29.97,30.94,NaN,7+,"1,600.00",NO,featured,2026-03-01T11:19:40Z,cash,Investment Building on Al Mehwar Al Markazi – ...,"73,178.00","6,438.00"
4064,Land,NaN,Land for Sale in October Gardens Prime Location,"10,500,000.00",Giza,6 October City,Hadayek October,29.91,31.07,NaN,NaN,426.00,NaN,featured,2026-02-26T10:21:56Z,cash,Prime Corner Plot for Sale in October Gardens ...,"72,021.00","6,399.00"
5609,Land,NaN,Prime Coastal Land Next to Siesta Marina,"265,000,000.00",North Coast,Al Alamein,NaN,30.82,28.95,NaN,NaN,"10,600.00",NaN,featured,2026-02-11T23:07:37Z,cash,Strategic freehold investment land directly on...,"68,246.00","6,316.00"
5722,Land,NaN,Residential Land for Development in a Fully In...,"2,400,000.00",Giza,6 October City,New October City,29.90,30.80,NaN,NaN,311.00,NaN,featured,2026-01-20T11:34:18Z,cash | installments,"Own residential land plots in Uptown October, ...","71,946.00","6,031.00"
5730,Land,NaN,فرصة نادرة جدا أرض فيو جاردن مباشر 4 شقق في الدور,"14,600,000.00",Cairo,New Cairo City,The 5th Settlement,30.06,31.55,NaN,NaN,935.00,NaN,featured,2026-03-01T10:04:26Z,cash,الموقع: الحي الخامس - بيت الوطن ثاني نمرة من P...,"58,306.00","2,832.00"
5742,Land,NaN,للبيع قطعة ارض 495 متر بجنوب السويس بالتجمع ال...,"15,000,000.00",Cairo,New Cairo City,The 5th Settlement,30.06,31.55,NaN,NaN,495.00,NaN,featured,2026-03-03T12:59:22Z,cash,للبيع قطعة ارض 495 متر بجنوب السويس بيت الوطن ...,"43,540.00","1,393.00"
5820,Land,NaN,للبيع قطعة أرض مميزة في أكتوبر الجديدة,"2,250,000.00",Giza,6 October City,New October City,29.90,30.80,NaN,NaN,100.00,NaN,featured,2026-02-25T22:39:53Z,installments,للبيع قطعة أرض مميزة في أكتوبر الجديدة تفاصيل ...,"49,913.00","5,527.00"
5894,Land,NaN,اب تاون مجاورة الأولي قطاع ٨ اميز سعر اصيل مباشر,"3,100,000.00",Giza,6 October City,New October City,29.90,30.80,NaN,NaN,311.00,NaN,featured,2026-02-24T22:51:16Z,cash,فرصة مميزة – قطعة أرض للبيع في حي Uptown، أكتو...,"31,467.00","3,014.00"
5895,Land,NaN,اب تاون مج الرابعه بحري صر,"3,000,000.00",Giza,6 October City,Green Belt,29.89,30.84,NaN,NaN,311.00,NaN,featured,2026-02-24T22:41:57Z,cash,فرصة مميزة – قطعة أرض للبيع في حي Uptown، أكتو...,"31,467.00","3,014.00"
6023,Land,NaN,للبيع قطعة ارض 459 متر بشمال الرحاب التجمع,"11,000,000.00",Cairo,New Cairo City,North Rehab,30.04,31.47,NaN,NaN,459.00,NaN,featured,2026-02-21T12:38:36Z,cash,للبيع قطعة ارض 459 متر بشمال الرحاب التجمع الا...,"43,540.00","1,393.00"
6091,Land,NaN,دبل فيس 2550 م بالغرود الشرقية جمعية عرابي العبور,"13,500,000.00",Qalyubia,Obour City,Gamaiet Ahmed Orabi,30.21,31.52,NaN,NaN,"1,683.00",NaN,featured,2026-02-17T09:59:59Z,cash,للتميز .. بموقع لن يتكرر قطعة ارض دبل فيس مساح...,"16,226.00","1,505.00"
6235,Land,NaN,اب تاون مجاورة الثانيه علي حديقه كبيره وشارع ك...,"4,000,000.00",Giza,6 October City,New October City,29.90,30.80,NaN,NaN,322.00,NaN,featured,2026-02-06T19:25:17Z,cash,حي اب تاون ٦ اكتوبر قطعهومميزه مجاورة الثانيه ...,"31,467.00","3,014.00"
6256,Land,NaN,أرض للبيع بكورنيش النيل جاردن سيتي,"850,000,000.00",Cairo,Garden City,Nile Corniche St.,30.04,31.24,NaN,NaN,"1,100.00",NaN,featured,2026-03-01T14:57:17Z,cash,للبيع قطعة ارض بكورنيش النيل تطل مباشرتا علي ج...,"25,920.00","2,590.00"
6319,Land,NaN,ارض جرين اكتوبر ١٠٠٠ م نسبة المباني ٢٢.٥,"3,500,000.00",Giza,6 October City,Green Belt,29.93,30.83,NaN,NaN,400.00,NaN,featured,2026-02-04T10:34:01Z,cash,إسكان فاخر فقط السعر ٢ مليون ٤٠٠ فعلا السعر حق...,"31,467.00","3,014.00"
7745,Land,NaN,"Land 10 acres, 3 interfaces in very prime loca...","90,000,000.00",Giza,6 October City,Green Belt,29.95,30.80,NaN,NaN,"4,000.00",NaN,standard,2026-03-04T11:47:24Z,cash,"A plot of land for sale in the Green Belt, leg...","28,532.00","2,931.00"
9842,Land,NaN,Land for Sale in The Third Settlement,"350,000,000.00",Cairo,New Cairo City,The 5th Settlement,29.97,31.49,NaN,NaN,"12,000.00",NaN,standard,2026-03-03T15:50:16Z,cash,Code: S3342 Unit Specifications: New Cairo Lan...,"44,226.00","4,963.00"
9843,Land,NaN,Land for Sale in Fifth Settlement,"73,492,654.00",Cairo,New Cairo City,The 5th Settlement,30.06,31.55,NaN,NaN,450.00,NaN,standard,2026-03-03T15:49:56Z,cash,code-S3341 Unit Specifications: New Cairo Land...,"44,226.00","4,963.00"
10350,Land,NaN,"Land for sale on the Oasis Road, 6th of October","940,000,000.00",Giza,6 October City,Al Wahat Road,29.96,30.92,NaN,NaN,"96,600.00",NaN,standard,2026-03-03T13:35:51Z,cash,A 23-acre plot of land on the Oasis Road Price...,"53,051.00","5,778.00"
10358,Land,NaN,"Land for sale on the Oasis Road, 6th of October","940,000,000.00",Giza,6 October City,Al Wahat Road,29.96,30.92,NaN,NaN,"96,600.00",NaN,standard,2026-03-03T13:32:48Z,cash,A 23-acre plot of land on the Oasis Road Price...,"53,051.00","5,778.00"
10419,Land,NaN,"Land for sale in the Green Belt, prime location","140,000,000.00",Giza,6 October City,Green Belt,30.03,30.94,NaN,NaN,"21,000.00",NaN,standard,2026-03-03T13:21:08Z,cash,"Land for sale in the Green Belt, prime locatio...","53,051.00","5,778.00"
10482,Land,NaN,"Land for sale in the Green Belt, prime location","140,000,000.00",Giza,6 October City,Green Belt,30.03,30.94,NaN,NaN,"21,000.00",NaN,standard,2026-03-03T13:11:44Z,cash,"Land for sale in the Green Belt, prime locatio...","53,051.00","5,778.00"
10500,Land,NaN,Land for sale in New Sheikh Zayed,"400,000,000.00",Giza,6 October City,Green Belt,30.06,30.93,NaN,NaN,"42,000.00",NaN,standard,2026-03-03T13:07:19Z,cash,"Land for sale, 42,000 square meters (10 acres)...","53,051.00","5,778.00"
11206,Land,NaN,"Land for sale in Sheikh Zayed, Al Ghoul Street","770,400,000.00",Giza,Sheikh Zayed City,Riviera City,30.05,31.05,NaN,NaN,"38,520.00",NaN,standard,2026-03-03T11:37:07Z,cash,"A very special plot of land Area: 38,520 squar...","53,051.00","5,778.00"
11568,Land,NaN,ارض للبيع بموقع مميز فى نيو جيزه 1360م موقع مميز,"75,000,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.06,NaN,NaN,"1,360.00",NaN,standard,2026-03-03T10:40:52Z,cash,Land for sale in a prime location in New Giza ...,"26,955.00","2,671.00"
15908,Land,NaN,Prime Corner Plot of Land for Sale In Beit AlW...,"18,000,000.00",Cairo,New Cairo City,The 5th Settlement,30.06,31.55,NaN,NaN,759.00,NaN,standard,2026-03-01T14:15:41Z,cash,code-S3709 Unit Specifications: New Cairo Prim...,"44,226.00","4,963.00"
17091,Bulk Sale Unit,off_plan,Resale 5 apartments same building as bulk Estates,"4,500,000.00",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.08,30.88,NaN,3,137.00,PARTLY,standard,2026-03-01T10:31:12Z,cash,Resale 5 apartments in same building as a bulk...,"71,979.00","6,397.00"
17634,Land,NaN,Land for sale in the Green Belt| prime Location,"120,000,000.00",Giza,6 October City,Green Belt,30.03,30.93,NaN,NaN,"14,000.00",NaN,standard,2026-03-01T01:40:51Z,cash,Land for sale in the Green Belt A very special...,"58,527.00","5,778.00"
18151,Land,NaN,Land for Sale in Fifth Settlement - Beit Al Watan,"23,000,000.00",Cairo,New Cairo City,The 5th Settlement,30.06,31.55,NaN,NaN,765.00,NaN,standard,2026-02-28T14:54:14Z,cash,code-S3822 Unit Specifications: New Cairo Land...,"44,226.00","4,963.00"
18838,Land,NaN,For Sale Residential Land Sheraton Almaza Airport,"85,000,000.00",Cairo,El Nozha,Sheraton Al Matar,30.10,31.37,NaN,NaN,"1,378.00",NaN,standard,2026-02-28T10:43:09Z,cash,For Sale | Residential Land – Sheraton (East o...,"47,149.00","1,321.00"

In [ ]:
rent[rent['bedrooms'].isna() | rent['bathrooms'].isna()]

,property_type,completion_status,title,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,listed_date,payment_method,description,agent_id,broker_id
21882,Bulk Rent Unit,NaN,افضل سعر ايجار لفيلا مفروشة بالكامل فى التجمع,"80,000.00",Cairo,New Cairo City,South Investors Area,30.01,31.49,NaN,5,500.00,YES,featured,2026-02-26T15:29:36Z,NaN,فيلا تاون هاوس 500م مفروشه ومكيفة مودرن بكمبون...,"67,325.00","6,290.00"
33708,Bungalow,NaN,Apartment for rent in the First District Villa...,"30,000.00",Cairo,New Cairo City,The 5th Settlement,30.01,31.43,NaN,3,350.00,NO,standard,2026-02-16T09:08:21Z,NaN,E12352B (B) Unfurnished apartment for rent in ...,"66,449.00","2,520.00"
39324,Bungalow,NaN,"Ground flr, private garden, furnished, prime loc.","49,255.00",Cairo,New Cairo City,North Investors Area,30.03,31.41,NaN,1,100.00,YES,standard,2026-02-08T12:11:59Z,NaN,Luxurious Studio for Rent in Cairo Festival Ci...,"60,076.00","6,095.00"

In [ ]:
re['bedrooms'].describe()

count     39678
unique        9
top           3
freq      18189
Name: bedrooms, dtype: object

In [ ]:
re['bathrooms'].describe()

count     39683
unique        9
top           3
freq      14168
Name: bathrooms, dtype: object

In [ ]:
re['bathrooms'].value_counts(dropna=False)

bathrooms
3       14168
2       11037
4        6135
1        4452
5        2449
6         794
7         380
7+        260
NaN        30
none        8
Name: count, dtype: int64

## bedrooms and bathrooms Adjusting data types

In [ ]:
# Making bedrooms and bathrooms  Ordered Categorical

bed_order = ['studio', '1', '2', '3', '4', '5', '6', '7', '7+']
bath_order = ['none', '1', '2', '3', '4', '5', '6', '7', '7+']

for df in [sell, rent]:
    df['bedrooms'] = pd.Categorical(df['bedrooms'], categories=bed_order, ordered=True)
    df['bathrooms'] = pd.Categorical(df['bathrooms'], categories=bath_order, ordered=True)

In [ ]:
for dataframe in [rent, sell]:

  dataframe['listed_date'] = pd.to_datetime(dataframe['listed_date'])

  # Ensure agent_id and broker_id are treated as categorical/string IDs
  dataframe['agent_id'] = (
      dataframe['agent_id'].fillna(-1).astype(int).astype(str)
  )
  dataframe['broker_id'] = (
      dataframe['broker_id'].fillna(-1).astype(int).astype(str)
  )

## fill missings in 'furnished' ,'district'

In [ ]:
rent['furnished'].isna().sum()

np.int64(145)

In [ ]:
rent['furnished'] = rent['furnished'].fillna('Unknown')

In [ ]:
sell['furnished'].isna().sum()

np.int64(8240)

In [ ]:
sell['furnished'] = sell['furnished'].fillna('Unknown')

In [ ]:
rent['furnished'].value_counts(dropna=False)

furnished
YES        11285
PARTLY      5561
NO          2919
Unknown      145
Name: count, dtype: int64

In [ ]:
rent

,property_type,completion_status,title,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,listed_date,payment_method,description,agent_id,broker_id
19803,Apartment,NaN,First use semi furnished 2BR in El Patio Oro,"35,000.00",Cairo,New Cairo City,The 5th Settlement,30.03,31.59,2,2,128.00,PARTLY,premium,2026-03-04 21:13:08+00:00,NaN,Apartment with kitchen and air conditioning fo...,55901,5389
19804,Apartment,NaN,"Unfurnished apartment for rent with kitchen, a...","50,000.00",Cairo,New Cairo City,El Banafseg,30.05,31.47,3,3,300.00,NO,premium,2026-03-04 12:47:53+00:00,NaN,E14755 Unfurnished apartment for rent with kit...,66449,2520
19805,Apartment,NaN,Furnished apartment for rent in Al Yasmin 2 Vi...,"45,000.00",Cairo,New Cairo City,El Yasmeen,30.05,31.45,3,3,210.00,YES,premium,2026-03-04 11:12:17+00:00,NaN,E14748 Furnished apartment for rent in Al Yasm...,66449,2520
19806,Apartment,NaN,Unfurnished apartment for rent with air condit...,"25,000.00",Cairo,New Cairo City,Abou El Houl,29.98,31.47,2,2,150.00,NO,premium,2026-03-04 10:58:28+00:00,NaN,E14745 Unfurnished apartment for rent with air...,50635,2520
19807,Apartment,NaN,Furnished apartment for rent behind Mirage Cit...,"40,000.00",Cairo,New Cairo City,The 1st Settlement,30.05,31.44,2,2,130.00,YES,premium,2026-03-04 09:19:33+00:00,NaN,E12494B Furnished apartment for rent behind Mi...,44158,2520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,Apartment,NaN,"Furnished apartment for rent in Al Rehab, 250M","55,000.00",Cairo,New Cairo City,Al Rehab,30.06,31.51,3,3,250.00,YES,standard,2026-02-07 16:33:32+00:00,NaN,Furnished apartment for rent in Al Rehab Phase...,68162,4456
39709,Apartment,NaN,FULLY FURNISHED apartment for RENT 3 Bedroom,"45,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.09,3,3,180.00,YES,standard,2026-02-07 16:32:23+00:00,NaN,"AVAILABLE MID AUGUST, 2025 An Elegant 3 Bedroo...",23636,430
39710,Townhouse,NaN,Furnished villa for rent in Town 5 rooms near New,"120,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.04,5,5,320.00,YES,standard,2026-02-07 16:31:32+00:00,NaN,Furnished villa for rent at a special price To...,16061,4679
39711,Apartment,NaN,For Rent – Premium 196m² Fully Finished Apartment,"50,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.06,2,2,196.00,NO,standard,2026-02-07 16:29:24+00:00,NaN,For Rent – Premium 196m² Fully Finished Apartm...,60109,430
39712,Apartment,NaN,If you're looking hotel units contact us now,"75,000.00",Cairo,New Cairo City,The 5th Settlement,30.02,31.55,2,2,144.00,YES,standard,2026-02-07 16:26:50+00:00,NaN,Unit Description: Location: Villette Compound ...,56917,5307

In [ ]:
rent.drop(columns=['completion_status'],inplace=True,errors='ignore') # nulls already
rent.drop(columns=['payment_method'],inplace=True,errors='ignore')

In [ ]:
#Filling the nan in'district'
sell['district'] = sell['district'].fillna(sell['town'])
rent['district'] = rent['district'].fillna(rent['town'])

In [ ]:
sell['price_per_sqm'] = sell['price_egp'] / sell['area_value']

In [ ]:
rent.isnull().sum()

property_type    0
title            0
price_egp        0
city             0
town             0
district         0
lat              0
lon              0
bedrooms         3
bathrooms        0
area_value       0
furnished        0
listing_level    0
listed_date      0
description      0
agent_id         0
broker_id        0
dtype: int64

In [ ]:
sell.isnull().sum()

property_type         1
completion_status    40
title                 1
price_egp             1
city                  1
town                  1
district              1
lat                   1
lon                   1
bedrooms             32
bathrooms            30
area_value            1
furnished             0
listing_level         1
listed_date           1
payment_method        1
description           1
agent_id              0
broker_id             0
price_per_sqm         1
dtype: int64

## **Duplicated rows**

No duplicate listing IDs does NOT mean no duplicate properties/listings.

It means only that the IDs are unique.

In [ ]:
re.duplicated().sum()

np.int64(0)

In [ ]:
re['listing_id'].duplicated().sum()

np.int64(0)

In [ ]:
duplicates_filter = ['property_type','completion_status','price_egp','city','town','district',
'lat','lon','bedrooms','bathrooms','area_value','furnished','listing_level','is_premium','is_featured'
,'payment_method','agent_id','broker_id'
      ]

In [ ]:
re.duplicated(subset=duplicates_filter).sum()

np.int64(2072)

In [ ]:
duplicate_mask = re.duplicated(
    subset=duplicates_filter,
    keep=False
)
duplicate_mask.sum()

np.int64(3506)

In [ ]:
duplicates_filter_rent = [
    'property_type',
    'price_egp',
    'city',
    'town',
    'district',
    'lat',
    'lon',
    'bedrooms',
    'bathrooms',
    'area_value',
    'furnished',
    'listing_level',
    'agent_id',
    'broker_id'
]

# Identify duplicates in 'rent' DataFrame, keeping only subsequent occurrences
rent_subsequent_duplicates = rent[rent.duplicated(subset=duplicates_filter_rent, keep='first')]

# Filter for furnished properties
furnished_condition = rent_subsequent_duplicates['furnished'].str.upper().eq('YES')

# Filter for specific districts
district_condition = rent_subsequent_duplicates['district'].isin([
    'Marassi', 'Ras Al Hekma', 'La vista Ras El Hikma', 'Marassi Bay', 'Seashell'
])

# Apply all conditions to get the final filtered duplicates
filtered_duplicates_count = rent_subsequent_duplicates[furnished_condition & district_condition].shape[0]

print(f"Number of furnished duplicate properties in specified districts (excluding first observation): {filtered_duplicates_count}")

Number of furnished duplicate properties in specified districts (excluding first observation): 0

Let's first check the unique 'town' values and their counts within the `furnished_duplicates` DataFrame to see if there are any unexpected entries.

In [ ]:
re.drop_duplicates(
    subset=['property_type', 'price_egp', 'lat', 'lon', 'area_value', 'bedrooms', 'bathrooms', 'description'],
    keep='first',
    inplace=True,
    ignore_index=True
)

## **2 dataframs cleaning**

### dealing with wrong 'area_value' in rent dataframe

drop rows with less than 20m2 in rent as all of them is wrong

In [ ]:
#investigate the sucpesious 'area_value'
(rent['area_value'] <= 20).sum()

np.int64(5)

In [ ]:
rent = rent[rent['area_value'] > 20]

In [ ]:
rent.shape

(19905, 17)

### dealing with wrong 'area_value' in sell dataframe

investigate the problematic rows

In [ ]:
(sell['area_value'] <=20).sum()

np.int64(1457)

In [ ]:
sell[(sell['area_value'] <=20)].head(100)

,property_type,completion_status,title,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,listed_date,payment_method,description,agent_id,broker_id,price_per_sqm
61,Villa,completed_primary,villa275m ready to move finished with DP1.8mil...,"1,800,000.00",Giza,6 October City,6th District,30.01,30.93,4,4,20.00,NO,premium,2026-03-04 12:06:03+00:00,cash,Ready-to-move-in fully finished standalone vil...,61112,6005,"90,000.00"
65,Villa,completed_primary,villa275m ready to move finished with DP1.8mil...,"1,800,000.00",Giza,6 October City,6 October Compounds,29.99,31.08,4,4,20.00,NO,premium,2026-03-04 12:04:40+00:00,cash,Ready-to-move-in fully finished standalone vil...,61112,6005,"90,000.00"
75,Apartment,completed_primary,ready to move finished Apt. 195m + 8Y Installment,"2,500,000.00",Giza,6 October City,6 October Compounds,29.91,30.67,3,3,20.00,PARTLY,premium,2025-12-21 11:32:20+00:00,cash,Immediate Delivery fully finished Apartment – ...,59409,1168,"125,000.00"
80,Villa,completed_primary,"luxury villa 229m + quarterly installment 610,000","610,000.00",Giza,Sheikh Zayed City,6th District,30.04,30.99,4,4,1.00,Unknown,premium,2026-03-04 11:08:44+00:00,cash,Townhouse in a Prime Location on 26th of July ...,59409,1168,"610,000.00"
138,Apartment,completed_primary,Apartment 134m² (finished and ready for handover),"900,000.00",North Coast,Al Alamein,Marina,30.84,28.97,1,1,20.00,NO,premium,2026-02-25 12:21:03+00:00,cash,"For Sale in Lower Egypt, in the Latin District...",42206,3655,"45,000.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,Villa,completed_primary,"town210m ready to move finished with a DP 825,000","825,000.00",Giza,6 October City,6 October Compounds,29.99,31.08,3,3,20.00,NO,premium,2026-02-24 12:20:55+00:00,cash,"Townhouse for immediate occupancy, fully finis...",61112,6005,"41,250.00"
1470,Apartment,completed_primary,"With a 5% down payment of only 178,000, you ca...","356,000.00",Cairo,New Cairo City,The 5th Settlement,30.06,31.55,3,2,20.00,Unknown,premium,2026-02-24 11:50:44+00:00,cash | installments,"With a 5% down payment of only 178,000, you ca...",64923,531,"17,800.00"
1515,Apartment,completed_primary,"DP1, 2M=Hot deal apt170sqm, special price, ready","1,200,000.00",Cairo,New Cairo City,The 1st Settlement,30.09,31.51,3,3,20.00,Unknown,premium,2026-02-22 22:17:51+00:00,cash,Ready for viewing now - Immediate occupancy Op...,70922,3655,"60,000.00"
1556,Chalet,completed_primary,"790,000 EGP = Rtm Sea View Fully Finished chal...","790,000.00",Suez,Al Ain Al Sokhna,IL Monte Galala,29.50,32.41,3,2,20.00,NO,premium,2026-02-23 18:21:57+00:00,cash | installments,"119m Panoramic Sea View 100% Fully Finished ,a...",70902,3655,"39,500.00"
1560,Apartment,completed_primary,1 millon Radytomove-Fullyfinshed in Sheraton,"1,000,000.00",Cairo,El Nozha,Sheraton Al Matar,30.09,31.38,2,2,20.00,NO,premium,2026-02-22 19:41:12+00:00,cash,Receive your fully finished apartment immediat...,70950,3655,"50,000.00"

In [ ]:
# making sure the suspicious area values are the same in original dataframe
(re['area_value'] <=20).sum() # 1457 in sell + 5 in rent = 1462 in re

np.int64(1348)

In [ ]:
# temporary dataframe that contains all properties with area <=20
small_sell = sell[sell['area_value'] <= 20].copy()

print("Number of suspicious sale records:", len(small_sell))

print("\nProperty types:")
print(small_sell['property_type'].value_counts())

print("\nArea distribution:")
print(small_sell['area_value'].value_counts().sort_index())

Number of suspicious sale records: 1457

Property types:
property_type
Apartment          839
Villa              342
Chalet             176
Duplex              37
Penthouse           29
Hotel Apartment     17
Twin House          11
iVilla               3
Whole Building       2
Palace               1
Name: count, dtype: int64

Area distribution:
area_value
1.00       23
2.00        6
3.00        1
5.00        3
6.00        1
10.00      35
11.00       3
12.00       1
14.00       5
15.00       2
16.00       1
17.00       1
20.00    1375
Name: count, dtype: int64

In [ ]:
pd.crosstab(
    small_sell['property_type'],
    small_sell['area_value']
)

area_value,1.00,2.00,3.00,5.00,6.00,10.00,11.00,12.00,14.00,15.00,16.00,17.00,20.00
property_type,,,,,,,,,,,,,
Apartment,0,0,0,0,0,0,0,0,0,0,0,0,839
Chalet,5,5,0,3,0,20,3,0,4,2,1,1,132
Duplex,1,0,0,0,0,0,0,0,0,0,0,0,36
Hotel Apartment,4,0,1,0,0,5,0,0,0,0,0,0,7
Palace,1,0,0,0,0,0,0,0,0,0,0,0,0
Penthouse,2,0,0,0,0,1,0,0,0,0,0,0,26
Twin House,1,0,0,0,0,0,0,0,0,0,0,0,10
Villa,9,1,0,0,1,9,0,1,1,0,0,0,320
Whole Building,0,0,0,0,0,0,0,0,0,0,0,0,2
iVilla,0,0,0,0,0,0,0,0,0,0,0,0,3

In [ ]:
#summation of titles in the new dataframe that contains the real area
small_sell['title'].str.extract(
    r'(\d+(?:\.\d+)?)\s*m(?:²|2)?\b',
    expand=False
).notna().sum()

np.int64(628)

In [ ]:
#show rows where titles contains the real area
small_sell[
    small_sell['title'].str.extract(
        r'(\d+(?:\.\d+)?)\s*m(?:²|2)?\b',
        expand=False
    ).notna()
][
    ['property_type', 'area_value', 'title']
].head(50)

,property_type,area_value,title
61,Villa,20.00,villa275m ready to move finished with DP1.8mil...
65,Villa,20.00,villa275m ready to move finished with DP1.8mil...
75,Apartment,20.00,ready to move finished Apt. 195m + 8Y Installment
80,Villa,1.00,"luxury villa 229m + quarterly installment 610,000"
138,Apartment,20.00,Apartment 134m² (finished and ready for handover)
155,Villa,20.00,Villa 757m Lowest price /Quarterly 827K Palm H...
157,Apartment,20.00,Ready-to-Move Garden Apartment160m per Q463K i...
159,Villa,20.00,Ready to move Villa220m Pool View 1.400M Quart...
163,Apartment,20.00,Apartment165m ReadytoMove Lagoons View Install...
168,Villa,20.00,Villa 522m ReadytoMove at Old Price on Install...
171,Villa,20.00,Villa540m 7Rooms on Instllment Behind MallofAr...
173,Apartment,20.00,Apartment 206m 806K DP With Longest Payment Plan
174,Villa,20.00,Villa538m with Pool Instllment Behind MallofAr...
175,Apartment,20.00,Ready to Move Aprtmnt 148m Resale Price Instal...
184,Penthouse,20.00,Last 275 m² 4-bd Zayed Near Ahly club Over14 y...
202,Apartment,20.00,"206m 3 rooms ,Service Aprtment Zayed over 10 y..."
203,Apartment,20.00,"Last 164 m, 3bd +large garden ReadyToMove inst..."
250,Apartment,20.00,Finished APt100m DP360.000 15Y installments Op...
251,Apartment,20.00,164m Finished Apartment New Cairo 650K Quarterly
391,Apartment,20.00,Apt130m finished ready to move with DP 2.2million
456,Apartment,20.00,Prime deal 130m garden apt near Mall of Arabia
475,Apartment,20.00,Last 164m² 3 bd View Pool ReadyTo Move +installme
518,Apartment,20.00,Apartment 140m + Garden ( Fully Finished ) RTM
563,Apartment,20.00,Cheapest apartment196m ready to move in 6 West
585,Chalet,10.00,"Finished 100m, Lake view, Lowest DP, till 2032"
661,Apartment,20.00,RTM Apartment171m at Landscape View on Install...
669,Apartment,20.00,Apart160m FullyFinish ReadytoMove in Zayed on ...
671,Apartment,20.00,Apart171m FullyFinishd & ACs+Ktchen Hotel Serv...
674,Villa,20.00,Villa 565m FullyFnish Ready to Move on Install...
717,Apartment,20.00,Ready To Move AP 138m With Discount 34% Or DP ...
795,Villa,20.00,Lowest price Villa 332m Finished Palm Hills+in...
798,Apartment,20.00,"DP 1500K,apartment(140m+garden)(RTM)-mountain ..."
799,Chalet,20.00,FinishedFinished+ACs Ch148m Amazing Sea View D...
801,Villa,20.00,Panoramic Sea View On Elevation 160m Ready Vie...
805,Duplex,20.00,"1,600,000 Only! Ready To Move Duplex 195m VIP ..."
806,Villa,20.00,"DP 1,000,000 Villa 150m Sea View Or Discount 4..."
807,Chalet,2.00,Cash Discount 40% Chalet 181m Direct Sea View
808,Chalet,10.00,"1,500,000= Chalet 182m + G First Row Steps To Sea"
809,Apartment,20.00,Ready To Move & Finished Apartment 154m Corner
810,Apartment,20.00,Ready To Move AP 138m With Discount 34% Or DP ...
811,Villa,20.00,Lowest Price 373m Villa in Sheikh Zayed near H...
813,Apartment,20.00,DP 600k=apt(100m+garden 118m+pool) finished-ta...
814,Apartment,20.00,DP(420k)=APT(199m+garden72m)from the Saudi Com...
816,Apartment,20.00,"DP 690k,apartment(132m),garden view,before mar..."
827,Apartment,20.00,"APT,195m finished with DP 1.8 million ,prime view"
830,Apartment,20.00,"Apt 205m finished+A,C with DP 1.4million prim ..."
1033,Chalet,20.00,Chalet Resale Panorama View 90m +R Finished Ma...
1105,Apartment,20.00,Apartment172m FullyFinish ReadytoMove Installment
1132,Villa,20.00,Villa373m in Sheikh Zayed-Lowest Price-Pool View
1156,Villa,20.00,350m Villa with Open View near Palm Hills –inst

In [ ]:
# create new column with the extracted area
small_sell['area_from_title'] = (
    small_sell['title']
    .str.extract(r'(\d+(?:\.\d+)?)\s*m(?:²|2)?\b', expand=False)
    .astype(float))

In [ ]:
small_sell['area_from_title'].shape # 1457 row (number of area <=20)

(1457,)

In [ ]:
print(small_sell['area_value'].isna().sum())

#number of area that will be recovered
print(small_sell['area_value'].notna().sum())

0
1457

In [ ]:
small_sell.loc[
    small_sell['area_from_title'].notna(),
    'area_from_title'
].sort_values().head(20)

19726    50.00
14013    50.00
18728    50.00
7838     50.00
13084    71.00
17917    84.00
1033     90.00
18160    90.00
9016     95.00
2954     95.00
6851     96.00
18153    96.00
9735     99.00
9768     99.00
13185   100.00
15409   100.00
7161    100.00
10925   100.00
7150    100.00
7160    100.00
Name: area_from_title, dtype: float64

In [ ]:
small_sell.loc[
    small_sell['area_from_title'].notna(),
    'area_from_title'
].sort_values().tail(20)

18615   377.00
18557   377.00
18563   377.00
18550   377.00
18580   377.00
18909   400.00
8167    400.00
18931   400.00
15465   420.00
168     522.00
174     538.00
171     540.00
674     565.00
19531   565.00
1965    566.00
16903   643.00
9331    757.00
9328    757.00
155     757.00
13190   757.00
Name: area_from_title, dtype: float64

In [ ]:
#the extract is almost true as range of values is normal
print(small_sell.shape)

print(small_sell['area_from_title'].notna().sum())

print(small_sell['area_from_title'].dtype)

print(small_sell['area_from_title'].describe())

(1457, 21)
628
float64
count   628.00
mean    207.76
std      97.12
min      50.00
25%     140.00
50%     180.00
75%     242.75
max     757.00
Name: area_from_title, dtype: float64

In [ ]:
# check if the most big area values match the property type
small_sell[
    small_sell['area_from_title'] > 500
][
    ['property_type', 'area_value', 'area_from_title', 'title']
]

,property_type,area_value,area_from_title,title
155,Villa,20.00,757.00,Villa 757m Lowest price /Quarterly 827K Palm H...
168,Villa,20.00,522.00,Villa 522m ReadytoMove at Old Price on Install...
171,Villa,20.00,540.00,Villa540m 7Rooms on Instllment Behind MallofAr...
174,Villa,20.00,538.00,Villa538m with Pool Instllment Behind MallofAr...
674,Villa,20.00,565.00,Villa 565m FullyFnish Ready to Move on Install...
1965,Villa,20.00,566.00,566m Villa 5-Settlement Finished By Palm Hills 9y
9328,Villa,20.00,757.00,Villa 757m Lowest price /Quarterly 827K Palm H...
9331,Villa,20.00,757.00,Villa 757m Lowest price /Quarterly 827K Palm H...
13190,Villa,20.00,757.00,Prime villa( 757m+3floors+open view+ full priv...
16903,Villa,20.00,643.00,"Fully finished 643m² standalone villa, lagoon ..."
19531,Villa,20.00,565.00,Villa 565m Ready to Move on Installment in SODIC

In [ ]:
# number of biggest area values
(small_sell['area_from_title'] > 500).sum()

np.int64(11)

 merge the extracted column in the sell dataframe

In [ ]:
small_sell.loc[
    small_sell['area_from_title'].notna(),
    'area_value'
] = small_sell.loc[
    small_sell['area_from_title'].notna(),
    'area_from_title'
]

In [ ]:
small_sell.loc[
    small_sell['area_from_title'].isna(),
    'area_value'
] = np.nan

In [ ]:
sell['area_status'] = 'Original'

In [ ]:
# merg 'area_from_title' with 'area_value' in 'area_status'
recovered = small_sell['area_from_title'].notna()

sell.loc[
    small_sell.index[recovered],
    'area_value'
] = small_sell.loc[
    recovered,
    'area_from_title'
]

In [ ]:
# label area values that coudn't be recovered as 'unknown'
unknown = small_sell['area_from_title'].isna()

sell.loc[
    small_sell.index[unknown],
    'area_value'
] = np.nan

sell.loc[
    small_sell.index[unknown],
    'area_status'
] = 'Unknown'

In [ ]:
#label 'area_value' that could be recoverd as recovered in 'area_status'
sell.loc[
    small_sell.index[recovered],
    'area_status'
] = 'Recovered'

In [ ]:
(sell['area_value'] <= 20).sum()

np.int64(0)

In [ ]:
#
(sell['area_status'] == 'Unknown').sum()

np.int64(829)

In [ ]:
# drop rows that can't be extracted from title
sell = sell[sell['area_status'] != 'Unknown'].copy()

### wrong listed properties

properties for rent listed in sell dataframe

In [ ]:
#Is price_egp always the actual sale price,
#or is it sometimes an installment/down-payment/displayed payment amount?

re[re['title'].str.contains(
    'quarter|monthly|down payment|installment|cash',
    case=False,
    na=False
)][[
    'price_egp',
    'price_period',
    'title'
]].head(30)

,price_egp,price_period,title
9,"23,250,000.00",sell,Swan Lake Gouna’s Last Unit — Flexible Install...
31,"6,500,000.00",sell,ready to move finished apt. 205m+148m installment
51,"450,000.00",sell,fully finished unit with ACs 153m-445K per qua...
64,"16,700,000.00",sell,Twinhouse for sale RTM -cash- very prime location
75,"2,500,000.00",sell,ready to move finished Apt. 195m + 8Y Installment
80,"610,000.00",sell,"luxury villa 229m + quarterly installment 610,000"
85,"130,000.00",sell,duplex in zayed with 130K per quarter-unit 233 m
87,"130,000.00",sell,duplex in zayed with 130K per quarter-unit 233 m
95,"8,700,000.00",sell,Chalet Opportunity With 0% Dp And Installments...
99,"3,370,500.00",sell,"""1-Bedroom Apartment in Ibiza – Down Payment 4..."
117,"8,700,000.00",sell,Rady for viewing and deliver finished installm...
124,"6,690,000.00",sell,"Apartment for sale with a down payment of 670,000"
127,"5,000,000.00",sell,APT + Garden over 15Y installments or 40% cash...
129,"11,900,000.00",sell,apartment 4 Bed with DP&installments- 238 SQM
133,"7,000,000.00",sell,"Apartment for sale with a down payment of 107,000"
134,"5,500,000.00",sell,"Apartment for sale in a garden, down payment 5..."
143,"37,600,000.00",sell,Villa with a 1.5% down payment + installments ...
144,"10,989,000.00",sell,144m² fully finished chalet in the Latin Quart...
145,"6,443,000.00",sell,Studio apartment for sale with a down payment ...
146,"7,000,000.00",sell,With700K dp from New Cairo near CFC installment
155,"827,000.00",sell,Villa 757m Lowest price /Quarterly 827K Palm H...
159,"1,428,824.00",sell,Ready to move Villa220m Pool View 1.400M Quart...
162,"3,000,000.00",sell,Apart182m FullyFinished ReadytoMove on Install...
163,"1,197,000.00",sell,Apartment165m ReadytoMove Lagoons View Install...
168,"6,200,000.00",sell,Villa 522m ReadytoMove at Old Price on Install...
172,"3,000,000.00",sell,villa 352m open view near palm hills + install...
176,"3,000,000.00",sell,finished apartment 180m with A\C +8yrs install...
178,"4,600,000.00",sell,"Ready apartment 170 m at lowest price, install..."
186,"3,659,400.00",sell,Chalet 57m on the sea with 4year installments
223,"300,000.00",sell,"120m finished chalet ,Marina view300K per quarter"

In [ ]:
#1489 value in the original data
(re['title'].str.contains(
    'quarter|monthly|quarterly|down payment|installment|cash',
    case=False,
    na=False
)).sum()

np.int64(1402)

In [ ]:
# new temporary dataframe
wrong_rent_in_sell = sell[
    sell['title'].str.contains(
        r'for rent|monthly rent|quarterly rent|per month|per quarter|per season',case=False,na=False,regex=True
    )
]

In [ ]:
wrong_rent_in_sell.shape #(9, 22)

(9, 21)

In [ ]:
wrong_rent_in_sell[
    ['price_egp','property_type','area_value','city','town','district','title']
].head(30)

,price_egp,property_type,area_value,city,town,district,title
51,"450,000.00",Apartment,153.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,fully finished unit with ACs 153m-445K per qua...
85,"130,000.00",Duplex,233.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,duplex in zayed with 130K per quarter-unit 233 m
87,"130,000.00",Apartment,233.00,Giza,Sheikh Zayed City,Ivoire,duplex in zayed with 130K per quarter-unit 233 m
223,"300,000.00",Chalet,120.00,Suez,Al Ain Al Sokhna,IL Monte Galala,"120m finished chalet ,Marina view300K per quarter"
497,"113,116.00",Apartment,155.00,Giza,6 October City,6 October Compounds,Finished Apartment155m+Garden for 113K per Qua...
2026,"474,525.00",Apartment,225.00,Giza,6 October City,6 October Compounds,RTM Finished iVilla 225m+Garden-474K per Quarter
2139,"155,220.00",Apartment,200.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Pay 52K per month&Get Finished Apartment in Zayed
2344,"5,500,000.00",Apartment,150.00,Alexandria,Hay Sharq,Smouha,"Apartment for rent, 210 sq m, Smouha (Grand View)"
8518,"8,000,000.00",Apartment,130.00,Cairo,New Cairo City,South Investors Area,Apartment for rent or sale in Galleria Moon Va...

In [ ]:
sell = sell.drop(index=wrong_rent_in_sell.index, errors='ignore')

properties for sell listed in rent dataframe

In [ ]:
# new temporary dataframe
wrong_sell_in_rent = rent[
    rent['title'].str.contains(
        r'for sell|sell|sale',case=False,na=False,regex=True
    )
]

In [ ]:
wrong_sell_in_rent[
    ['price_egp','property_type','area_value','city','town','district','title'
    ]
].head(30)

,price_egp,property_type,area_value,city,town,district,title
20001,"55,000.00",Apartment,186.00,Cairo,New Cairo City,The 5th Settlement,Apartment sale - Semi Furnished - Mivida
20124,"110,000.00",Villa,"1,000.00",Cairo,New Cairo City,Ext North Inves Area,Bellagio-semi Furnished Standalone 1000m For Sale
20150,"200,000.00",Villa,225.00,Cairo,New Cairo City,The 5th Settlement,VILLA 750M SALE IN MV1 WITH KITCHEN & ACS
20424,"25,000,000.00",Twin House,279.00,Giza,Sheikh Zayed City,6th District,Villa for sale - Greens Compound - Sheikh Zayed
20767,"15,000.00",Apartment,96.00,Cairo,Madinaty,Privado,Apartment 96m for sale in madinaty at B7
21071,"40,000.00",Apartment,150.00,Cairo,Hay El Manial,El Roda,"Apartment for rent, 150 sq m, King Saleh Stree..."
21502,"215,100.00",Apartment,327.00,Giza,Ganoub El Giza,Giza District,Luxury 5 Star Nile Apartment For Sale or Rent
21511,"215,000.00",Apartment,326.00,Giza,Dokki,Nile St.,Luxury 5 Star Nile Apartment For Sale or Rent
21516,"223,700.00",Apartment,297.00,Giza,Dokki,Nile St.,Nile serviced flat modern finish sale/rent 290m
21525,"7,750,000.00",Apartment,180.00,Cairo,New Cairo City,Al Narges,Ultra Super Lux Apartment for Sale with a Larg...
21647,"14,000.00",Apartment,103.00,Cairo,Madinaty,Privado,Apartment 103m for sale in madinaty at B6
22620,"10,000,000.00",Apartment,186.00,Cairo,New Cairo City,The 5th Settlement,Apartment for sale in Amorada With Fully AC'S
22675,"11,000,000.00",Apartment,216.00,Cairo,New Cairo City,Hyde Park,Apartment for Sale in Hyde Park - New Cairo
23372,"55,000.00",Apartment,235.00,Cairo,New Cairo City,The 5th Settlement,Ground Floor Apartment with Garden for Sale in...
23593,"100,000.00",Apartment,215.00,Cairo,New Cairo City,North Investors Area,Apartment for Sale or Rent in The Waterway Res...
23727,"75,000.00",Apartment,210.00,Cairo,New Cairo City,The 5th Settlement,Apartment for Sale in District 5 – Prime Location
24513,"8,000,000.00",Apartment,160.00,Cairo,New Cairo City,The 5th Settlement,Apartment for Sale in Prime Location at Park R...
24583,"145,000.00",Apartment,235.00,Cairo,New Cairo City,North Investors Area,Fully Furnished Apartment for sale in water way 1
25011,"192,000.00",Twin House,404.00,Cairo,New Cairo City,El Katameya,Luxury Twin Villa for Sale & Rent in Katameya ...
25790,"5,500,000.00",Apartment,185.00,Cairo,Nasr City,8th Zone,Apartment for sale in a prime location on Shinsoo
25818,"6,000,000.00",Apartment,210.00,Cairo,Nasr City,6th Zone,Apartment for sale in a prime location near Ma...
26372,"20,000.00",Apartment,143.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Apartment for sale with private garden.
26542,"90,000,000.00",Townhouse,250.00,Cairo,New Cairo City,Ext North Inves Area,Town House for sale in Dyar Park FF with AC's & K
26703,"128,000.00",Townhouse,285.00,Cairo,New Cairo City,The 5th Settlement,285sqm Resale Apt | Mivida | Great Price
26706,"18,620,000.00",Penthouse,235.00,Cairo,New Cairo City,South Investors Area,Penthouse for Sale in Golden Square – Galleria...
26999,"8,350,000.00",Apartment,160.00,Cairo,New Cairo City,The 5th Settlement,For Sale Fully Finished Penthouse in Trio Gardens
27157,"130,000.00",Villa,325.00,Cairo,New Cairo City,The 5th Settlement,Luxurious 4 Bedroom 325m² Villa for Sale in mi...
27626,"14,500,000.00",Apartment,149.00,Cairo,New Cairo City,The 5th Settlement,Apartment with garden for sale in District 5
27710,"193,000.00",Apartment,330.00,Cairo,Zamalek,Kamal Al Tawil St. (El Montazah),5-Star Nile-Facing Serviced Apartment for Sale...
27714,"193,100.00",Apartment,231.00,Cairo,Zamalek,Mohamed Abdel Wahab St.,5-Star Nile-Facing Serviced Apartment for Sale...

In [ ]:
wrong_sell_in_rent.shape

(96, 17)

In [ ]:
# properties for rent or sell in rent datafram
wrong_sell_in_rent['title'].str.contains(
    r'for sale or rent|sale/rent|sale & rent|for sale and rent',
    case=False,
    na=False,
    regex=True
).sum() # 20

# only 20 of properties for sell that is listed in rent df are for both rent and sell

np.int64(20)

In [ ]:
#drop the 96 worng raw
rent = rent.drop(index=wrong_sell_in_rent.index)

seasonal rent (not monthly)

In [ ]:
seasonal_mask = (
    rent['title'].str.contains(
        r'Seasonal Rent|per season|summer rent|summer rental',
        case=False,
        na=False,
        regex=True
    )
    |
    rent['description'].str.contains(
        r'Seasonal Rent|per season|summer rent|summer rental',
        case=False,
        na=False,
        regex=True
    )
)

seasonal_rent = rent[seasonal_mask].copy()

print("Seasonal listings:", len(seasonal_rent))

Seasonal listings: 21

In [ ]:
seasonal_rent[ 'title'].to_list()

['Lowest-priced apartment in Latin District, Alamein',
 'Premium Coastal Living for Rent in Marina Marassi',
 'Lowest-priced apartment in Latin District, Alamein',
 'Lowest-priced apartment in Latin District, Alamein',
 'For Seasonal Rent Chalet - Amwaj - North Coast',
 'For seasonal rent Chalet - Marassi',
 'For Seasonal Rent Penthouse Pool View, Amwaj',
 'Lowest-priced apartment in Latin District, Alamein',
 '70m Luxury Rent Apt | Latin District | Best Price',
 'Lowest-priced apartment in Latin District, Alamein',
 'Lowest-priced apartment in Latin District, Alamein',
 'Lowest-priced apartment in Latin District, Alamein',
 'Lowest-priced apartment in Latin District, Alamein',
 'A different level of privacy in hacienda bay',
 'Luxury Marina Chalet Rent in Marassi – Prime View',
 'sea view twin house for rent per season',
 'studio for seasonal rent - maeina 2 , marassi',
 'For Seasonal Rent Chalet with Garden - Marassi',
 'chalet for Seasonal Rent- marina marassi',
 'Chalet for rent Good view and prime location',
 'For Seasonal Rent Chalet Pool View - Amwaj']

In [ ]:
seasonal_rent[ 'description'].to_list()

["Apartment at the lowest price in the Latin District, in the heart of New Alamein. -------------------- Unit type: apartment Unit area: 140M square meters --------------------------- Total price : 60,000 monthly per season ---------------------- Features of LATIN DISTRICT : ----------------------- The New Alamein Life seeks the Latin District of New Alamein, one of the largest projects donated by the Saudi Egyptian Company in New Alamein, to compete for the award to attend the summer atmosphere in the most beautiful areas, and this area requires its great proximity to the most important vital and famous landmarks, which include distinctive. Absolute luxury. The necessity of having an unparalleled group of studios and chalets that determine the basic elements for customers mainly in reading the most important of them, as the company's location was chosen in the most vital areas of New Alamein so that residents are at a certain degree of distinctive landmarks that include everything they include. On the other hand, a better project is designed to design designers and architects with new experiences, which came with their new experiences in implementing it according to the latest international standards so that they are for those seeking high taste from customers, and they also achieve diversity in unit groups to satisfy a large segment of customers whether they want a small or large space, which guarantees you psychological comfort at all times. ------------------------------------------------ For more information call: 01092892866",
 'Experience luxurious coastal living in this meticulously designed unit at Marina Marassi. Master Suite with a king-size bed and elegant finishes Kids Room with two double beds Cleverly hidden extra bed behind the TV unit for unexpected guests Spacious living area centered around a 55-inch LG Smart TV 2 modern bathrooms with premium fixtures Fully equipped American-style kitchen with high-end dishwasher and coffee machine Separate laundry room with washing machine BUA: 140 sqm Asking Price: 950,000 EGP per season',
 "Apartment at the lowest price in the Latin District, in the heart of New Alamein. -------------------- Unit type: Apartment Unit area: 95M square meters --------------------------- Total price : 660,000 EGP monthly per season ---------------------- Features of LATIN DISTRICT : ----------------------- The New Alamein Life seeks the Latin District of New Alamein, one of the largest projects donated by the Saudi Egyptian Company in New Alamein, to compete for the award to attend the summer atmosphere in the most beautiful areas, and this area requires its great proximity to the most important vital and famous landmarks, which include distinctive. Absolute luxury. The necessity of having an unparalleled group of studios and chalets that determine the basic elements for customers mainly in reading the most important of them, as the company's location was chosen in the most vital areas of New Alamein so that residents are at a certain degree of distinctive landmarks that include everything they include. On the other hand, a better project is designed to design designers and architects with new experiences, which came with their new experiences in implementing it according to the latest international standards so that they are for those seeking high taste from customers, and they also achieve diversity in unit groups to satisfy a large segment of customers whether they want a small or large space, which guarantees you psychological comfort at all times. ------------------------------------------------ For more information call: 01092892866",
 "Apartment at the lowest price in the Latin District, in the heart of New Alamein. -------------------- Unit type: Apartment Unit area: 145M square meters --------------------------- Total price : 330,000 EGP monthly per season ---------------------- Features of LATIN DISTRICT : ----------------------- The New Alamein Life seeks the Latin District of New Alamein, one of the largest projects donated by the Saudi Egyptian Company in New Alamein, to compete for the award to attend the summer atmosphere in the most beautiful areas, and this area requires its great proximity to the most important vital and famous landmarks, which include distinctive. Absolute luxury. The necessity of having an unparalleled group of studios and chalets that determine the basic elements for customers mainly in reading the most important of them, as the company's location was chosen in the most vital areas of New Alamein so that residents are at a certain degree of distinctive landmarks that include everything they include. On the other hand, a better project is designed to design designers and architects with new experiences, which came with their new experiences in implementing it according to the latest international standards so that they are for those seeking high taste from customers, and they also achieve diversity in unit groups to satisfy a large segment of customers whether they want a small or large space, which guarantees you psychological comfort at all times. ------------------------------------------------ For more information call: 01092892866",
 'For Seasonal Rent Chalet - Amwaj - North Coast Prim Location Pool view Bua : 110 sqm First Floor Consists Of : 2 Bedrooms - 1 Bathrooms - Kitchen - Reception Seasonal Rent : 440,000 -- Contact : 01000720520 -- About Developer : Al-Ahly Sabbour Company (Al-Ahly Real Estate Development Company) was established in 1994 by Engineer Hassan Sabbour, the Chairman of the Board of Directors, who owns 60% of the company’s shares, and 40% for the National Bank of Egypt. The company was named after Al-Ahly Sabbour for Real Estate Development. Engineer Hassan Sabbour appointed the most skilled engineers and sought the help of experts from abroad to implement real estate projects that match the developments of the current era and what appears new in it. The company has provided the best services, facilities and recreational activities that delight customers. It has also been keen to allocate the majority of the space to green spaces to make you feel as if you are living in a wonderful forest full of trees and plants. The company has also provided security and safety in all its projects in order to preserve the customer’s comfort and safety. About Project : It is one of the most luxurious tourist villages, which was established in the recent period. To provide all the basic and recreational requirements, this distinctive village helps you enjoy the calm natural atmosphere and the fresh air that many customers are looking for. Location : Amwaj North Coast is located at kilometre 135 in Sidi Abdel Rahman area, specifically on Alexandria-Matrouh road. Therefore, it is close to many vital areas and axes, all of which are evident in the following: - Fouka Road: it is only 10 minutes away from Amwaj North Coast. - Marassi Village: It is 5 minutes away from the village site. - Sea Shell: It can be reached from Amwaj North Coast Village in 6 minutes. - Hacienda Bay: It is only about 8 minutes away from the resort.',
 'For seasonal rent Chalet - Marassi - Catania - North Coast Prime Location First Floor Bua : 150 Sqm Consists Of : 3 bedrooms - 2 bathrooms - reception - kitchen Maid Room Seasonal rent 600,000 - Contact : 01000720520 -- About Developer : The transformation and development in lifestyles over the years since 1997, has been a step towards the world of Emaar, where a life of luxury and vibrant development with its prestigious and wonderful communities, and with Emaar retaining its name and position as one of the largest and most advanced real estate developers in the world, Today, at Emaar Misr, we celebrate more than 15 years of achievements with its distinguished communities across the most distinguished and most beautiful destinations in Egypt About Marassi : Marassi is an unparalleled coastal destination on the northern Egyptian coast. It extends over more than 6.5 million square meters. Marassi includes 5 beaches, 23 residential communities, 3,300 hotel rooms, and an 18-hole golf course, in addition to one of the largest international marinas in the Middle East. Which makes it the jewel of the North Coast ..',
 'For Seasonal Rent Penthouse Pool View - Amwaj - North Coast Prime location - facing north Second floor Area : 164 Sqm Roof area : 164 Sqm Consists : 4 Bedrooms - 2 Bathrooms - Reception - Kitchen Seasonal rent : 520,000 -- Contact : 01000720520 -- About Developer : Al-Ahly Sabbour Company (Al-Ahly Real Estate Development Company) was established in 1994 by Engineer Hassan Sabbour, the Chairman of the Board of Directors, who owns 60% of the company’s shares, and 40% for the National Bank of Egypt. The company was named after Al-Ahly Sabbour for Real Estate Development. Engineer Hassan Sabbour appointed the most skilled engineers and sought the help of experts from abroad to implement real estate projects that match the developments of the current era and what appears new in it. The company has provided the best services, facilities and recreational activities that delight customers. It has also been keen to allocate the majority of the space to green spaces to make you feel as if you are living in a wonderful forest full of trees and plants. The company has also provided security and safety in all its projects in order to preserve the customer’s comfort and safety. About Project : It is one of the most luxurious tourist villages, which was established in the recent period. To provide all the basic and recreational requirements, this distinctive village helps you enjoy the calm natural atmosphere and the fresh air that many customers are looking for. Location : Amwaj North Coast is located at kilometre 135 in Sidi Abdel Rahman area, specifically on Alexandria-Matrouh road. Therefore, it is close to many vital areas and axes, all of which are evident in the following: - Fouka Road: it is only 10 minutes away from Amwaj North Coast. - Marassi Village: It is 5 minutes away from the village site. - Sea Shell: It can be reached from Amwaj North Coast Village in 6 minutes. - Hacienda Bay: It is only about 8 minutes away from the resort.',
 "Apartment at the lowest price in the Latin District, in the heart of New Alamein. -------------------- Unit type: Furnished Apartment Unit area: 62M square meters --------------------------- Total price : 120,000 EGP monthly per season ---------------------- Features of LATIN DISTRICT : ----------------------- The New Alamein Life seeks the Latin District of New Alamein, one of the largest projects donated by the Saudi Egyptian Company in New Alamein, to compete for the award to attend the summer atmosphere in the most beautiful areas, and this area requires its great proximity to the most important vital and famous landmarks, which include distinctive. Absolute luxury. The necessity of having an unparalleled group of studios and chalets that determine the basic elements for customers mainly in reading the most important of them, as the company's location was chosen in the most vital areas of New Alamein so that residents are at a certain degree of distinctive landmarks that include everything they include. On the other hand, a better project is designed to design designers and architects with new experiences, which came with their new experiences in implementing it according to the latest international standards so that they are for those seeking high taste from customers, and they also achieve diversity in unit groups to satisfy a large segment of customers whether they want a small or large space, which guarantees you psychological comfort at all times. ------------------------------------------------ For more information call: 01092892866",
 "Apartment at the lowest price in the Latin District, in the heart of New Alamein. -------------------- Unit type: Furnished Apartment with ACs Unit area: 70M square meters --------------------------- Total price : 90,000EGP monthly per season ---------------------- Features of LATIN DISTRICT : ----------------------- The New Alamein Life seeks the Latin District of New Alamein, one of the largest projects donated by the Saudi Egyptian Company in New Alamein, to compete for the award to attend the summer atmosphere in the most beautiful areas, and this area requires its great proximity to the most important vital and famous landmarks, which include distinctive. Absolute luxury. The necessity of having an unparalleled group of studios and chalets that determine the basic elements for customers mainly in reading the most important of them, as the company's location was chosen in the most vital areas of New Alamein so that residents are at a certain degree of distinctive landmarks that include everything they include. On the other hand, a better project is designed to design designers and architects with new experiences, which came with their new experiences in implementing it according to the latest international standards so that they are for those seeking high taste from customers, and they also achieve diversity in unit groups to satisfy a large segment of customers whether they want a small or large space, which guarantees you psychological comfort at all times. ------------------------------------------------ For more information call: 01092892866",
 "Apartment at the lowest price in the Latin District, in the heart of New Alamein. -------------------- Unit type: Furnished Apartment with ACs Unit area: 135M square meters --------------------------- Total price : 25,000 EGP monthly per season Season: 350,000 EGP ---------------------- Features of LATIN DISTRICT : ----------------------- The New Alamein Life seeks the Latin District of New Alamein, one of the largest projects donated by the Saudi Egyptian Company in New Alamein, to compete for the award to attend the summer atmosphere in the most beautiful areas, and this area requires its great proximity to the most important vital and famous landmarks, which include distinctive. Absolute luxury. The necessity of having an unparalleled group of studios and chalets that determine the basic elements for customers mainly in reading the most important of them, as the company's location was chosen in the most vital areas of New Alamein so that residents are at a certain degree of distinctive landmarks that include everything they include. On the other hand, a better project is designed to design designers and architects with new experiences, which came with their new experiences in implementing it according to the latest international standards so that they are for those seeking high taste from customers, and they also achieve diversity in unit groups to satisfy a large segment of customers whether they want a small or large space, which guarantees you psychological comfort at all times. ------------------------------------------------ For more information call: 01092892866",
 "Apartment at the lowest price in the Latin District, in the heart of New Alamein. -------------------- Unit type: Furnished Apartment with ACs Unit area: 177M square meters --------------------------- Total price : 175,000EGP monthly per season Season: 450,000 EGP ---------------------- Features of LATIN DISTRICT : ----------------------- The New Alamein Life seeks the Latin District of New Alamein, one of the largest projects donated by the Saudi Egyptian Company in New Alamein, to compete for the award to attend the summer atmosphere in the most beautiful areas, and this area requires its great proximity to the most important vital and famous landmarks, which include distinctive. Absolute luxury. The necessity of having an unparalleled group of studios and chalets that determine the basic elements for customers mainly in reading the most important of them, as the company's location was chosen in the most vital areas of New Alamein so that residents are at a certain degree of distinctive landmarks that include everything they include. On the other hand, a better project is designed to design designers and architects with new experiences, which came with their new experiences in implementing it according to the latest international standards so that they are for those seeking high taste from customers, and they also achieve diversity in unit groups to satisfy a large segment of customers whether they want a small or large space, which guarantees you psychological comfort at all times. ------------------------------------------------ For more information call: 01092892866",
 "Apartment at the lowest price in the Latin District, in the heart of New Alamein. -------------------- Unit type: apartment Unit area: 124M square meters --------------------------- Total price : 72,000monthly per season ---------------------- Features of LATIN DISTRICT : ----------------------- The New Alamein Life seeks the Latin District of New Alamein, one of the largest projects donated by the Saudi Egyptian Company in New Alamein, to compete for the award to attend the summer atmosphere in the most beautiful areas, and this area requires its great proximity to the most important vital and famous landmarks, which include distinctive. Absolute luxury. The necessity of having an unparalleled group of studios and chalets that determine the basic elements for customers mainly in reading the most important of them, as the company's location was chosen in the most vital areas of New Alamein so that residents are at a certain degree of distinctive landmarks that include everything they include. On the other hand, a better project is designed to design designers and architects with new experiences, which came with their new experiences in implementing it according to the latest international standards so that they are for those seeking high taste from customers, and they also achieve diversity in unit groups to satisfy a large segment of customers whether they want a small or large space, which guarantees you psychological comfort at all times. ------------------------------------------------ For more information call: 01092892866",
 "Apartment at the lowest price in the Latin District, in the heart of New Alamein. -------------------- Unit type: apartment Unit area: 122M square meters --------------------------- Total price : 36,000 monthly per season ---------------------- Features of LATIN DISTRICT : ----------------------- The New Alamein Life seeks the Latin District of New Alamein, one of the largest projects donated by the Saudi Egyptian Company in New Alamein, to compete for the award to attend the summer atmosphere in the most beautiful areas, and this area requires its great proximity to the most important vital and famous landmarks, which include distinctive. Absolute luxury. The necessity of having an unparalleled group of studios and chalets that determine the basic elements for customers mainly in reading the most important of them, as the company's location was chosen in the most vital areas of New Alamein so that residents are at a certain degree of distinctive landmarks that include everything they include. On the other hand, a better project is designed to design designers and architects with new experiences, which came with their new experiences in implementing it according to the latest international standards so that they are for those seeking high taste from customers, and they also achieve diversity in unit groups to satisfy a large segment of customers whether they want a small or large space, which guarantees you psychological comfort at all times. ------------------------------------------------ For more information call: 01092892866",

In [ ]:
rent = rent.drop(index=seasonal_rent.index)

### suspicious price

dealing with very low price listings in sell

In [ ]:
# after considring the smallest prices, i found that the properiate condition are :
very_low_sell = sell[(sell['price_egp'] < 300000)& (sell['area_value'] >70)]

very_low_sell[
    ['price_egp', 'property_type', 'area_value',
     'city', 'town', 'district', 'title']
]

Empty DataFrame
Columns: [price_egp, property_type, area_value, city, town, district, title]
Index: []

dealing with very low price listings in rent

In [ ]:
# after considring the smallest prices, it has been founded that properties with prica<3000 and area>70 must be wrong
# so i droped them
very_low_rent = rent[
    (rent['price_egp'] < 3000) &
    (rent['area_value'] > 70)
]

# Display specific columns
very_low_rent[['price_egp', 'property_type', 'area_value', 'city', 'town', 'district', 'title','description']]

,price_egp,property_type,area_value,city,town,district,title,description
20445,"2,200.00",Apartment,400.00,Cairo,New Cairo City,El Katameya,Apartment Semi Furnished at katameya DUNES,Compound name: Katameya Dunes ...................
20561,"2,200.00",Apartment,190.00,Cairo,New Cairo City,The 5th Settlement,3-bedroom apartment for rent fully Furniture LVR1,AZ1_220 Apartment for rent in Lake view 3bedro...
20563,"1,800.00",Apartment,268.00,Cairo,New Cairo City,The 5th Settlement,3-bedroom apartment for rent with kitchen &AC ...,AZ1_222 APARTMENT FOR RENT IN LAKE VIEW BUA:26...
20565,"1,300.00",Apartment,157.00,Cairo,New Cairo City,The 5th Settlement,Apartment for rent in Lake View Residence – 2 bed,AZ1_223 APARTMENT FOR RENT IN LAKE VIEW BUA:15...
20586,"1,700.00",iVilla,278.00,Cairo,New Cairo City,The 5th Settlement,Apartment for rent 4bedroom in MV Hyde park,MMS-2_252 Apartment for rent Mountain View Hyd...
20587,"1,400.00",Villa,180.00,Cairo,New Cairo City,The 5th Settlement,Villa for rent 3bedroom in Mountain View i city,MM-2_251 One story for rent Mountain View icit...
20901,"2,000.00",Villa,355.00,Cairo,New Cairo City,The 5th Settlement,Premium Villa with private pool in Mivida,] Premium Villa for Rent in Mivida with privat...
21056,"1,400.00",Apartment,210.00,Cairo,New Cairo City,The 5th Settlement,apartment 210m semi furnished rent eastown sodic,apartment 210m semi furnished for rent eastown...
21646,"1,750.00",Apartment,170.00,Cairo,New Cairo City,North Investors Area,Apartment for rent 2bed in CFC,AZ_13 CFC 4bathroom 2room Nanni Dua:170m Rent ...

In [ ]:
very_low_rent['description'];

In [ ]:
# rent = rent.drop(index=very_low_rent.index)

outlier , duplicates, conditions in terminating low rent prices , twon filter

dealing with very high rental price



---

we dealt with extremly low prices/areas by correcting or dropping as it's opvious their values are worgly listed


---

also with suspecious high price in rent dataset, the rest of very high prices in both sell and rent datasets are left for statistics phase

In [ ]:
rent.nlargest(60, 'price_egp')[
    ['price_egp', 'property_type',
     'area_value', 'city', 'town', 'district',
     'title', 'listed_date']
]

,price_egp,property_type,area_value,city,town,district,title,listed_date
33739,"185,000,000.00",Townhouse,260.00,Cairo,New Cairo City,South Investors Area,Town house for rent in la Terra furnished and ...,2026-02-16 07:56:37+00:00
20818,"160,000,000.00",Villa,357.00,Giza,6 October City,Cairo Alexandria Desert Road,Villa for Rent | New Giza Compound-Fully Finis...,2026-03-02 13:32:39+00:00
27617,"130,000,000.00",Townhouse,320.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,For Rent fully furnished townhouse at allegria,2026-02-25 12:01:08+00:00
21275,"125,000,000.00",Townhouse,380.00,Giza,6 October City,Al Wahat Road,Luxurious Corner Town House in Golf Extension,2026-02-20 12:38:21+00:00
37982,"70,000,000.00",Apartment,122.00,Cairo,New Cairo City,The 5th Settlement,Apartment For Rent Fully Furnished Prime location,2026-02-09 16:47:00+00:00
28881,"60,000,000.00",Palace,"2,500.00",North Coast,Sidi Abdel Rahman,Marassi,"Marassi Palace, first row on the sea, ultra super",2026-02-24 00:09:43+00:00
32815,"37,000,000.00",Villa,360.00,Cairo,New Cairo City,The 5th Settlement,Very prime location Villa Ready to move In PK2,2026-02-17 12:08:11+00:00
37865,"28,113,558.00",Villa,800.00,Cairo,New Cairo City,Hyde Park,Stand alone villa for rent at hyde park new comp,2026-02-09 21:24:46+00:00
32827,"24,600,000.00",Townhouse,257.00,Cairo,New Cairo City,The 5th Settlement,Very prime location town house best price in PK2,2026-02-17 11:57:55+00:00
37860,"21,085,812.00",Twin House,290.00,Cairo,New Cairo City,Hyde Park,win villa for rent at Hyde Park Built up area 290,2026-02-09 21:48:14+00:00
31626,"16,000,000.00",Apartment,211.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Zed Towers View on Sheikh Zayed nice view,2026-02-26 19:23:57+00:00
23113,"15,890,000.00",Apartment,162.00,Cairo,New Cairo City,The 5th Settlement,Luxury Apartment in Sodic Villette 5th Settlement,2026-03-03 13:32:00+00:00
23211,"15,000,000.00",Duplex,245.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Premium finishing – Prime location,2026-03-03 12:50:00+00:00
38152,"15,000,000.00",Villa,400.00,Cairo,New Cairo City,The 5th Settlement,Standalone Villa for Rent in Stone Park Compound,2026-02-09 14:11:09+00:00
38232,"13,000,000.00",Apartment,200.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Opportunity to invest _ under market price,2026-02-09 13:35:28+00:00
27915,"12,750,000.00",Apartment,198.00,Cairo,New Cairo City,The 5th Settlement,Apartment Bahary Fully Finished In Water Way,2026-02-25 09:32:04+00:00
23155,"12,500,000.00",Apartment,200.00,Cairo,New Cairo City,The 5th Settlement,Apartment view Club House in Waterway The View,2026-03-03 13:05:46+00:00
31340,"11,750,000.00",Apartment,163.00,Cairo,New Cairo City,The 5th Settlement,Exclusive APT161M view landscape Eastown main ...,2026-02-20 09:43:08+00:00
30895,"11,588,100.00",Apartment,118.00,Cairo,New Cairo City,Hyde Park,Apartment Under Market Price -With Installments,2026-02-21 13:58:00+00:00
37398,"10,500,000.00",Apartment,140.00,Cairo,New Cairo City,The 5th Settlement,apartment with a stunning garden and Ac's Marssem,2026-02-10 13:27:38+00:00
21221,"9,000,000.00",Villa,387.00,North Coast,Sidi Abdel Rahman,Marassi,Luxury Villa with Sea View at marassi bay,2025-05-14 18:39:01+00:00
21807,"8,500,000.00",Apartment,67.00,Giza,6 October City,6 October Compounds,اقل سعر ستوديو ف ابراج ايون مراكز - مول العرب,2026-02-21 18:22:52+00:00
22297,"6,600,000.00",Apartment,132.00,Cairo,Madinaty,Privado,132m View Garden Seafront next to South Park,2026-03-04 14:00:46+00:00
39114,"6,000,000.00",Apartment,235.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Ground-Floor Apartment with Front Garden,2026-02-08 14:57:36+00:00
22047,"5,300,000.00",Apartment,96.00,Cairo,Madinaty,Privado,Special finishing - Garden view - Next to Sout...,2026-03-04 19:34:07+00:00
36358,"4,300,000.00",Apartment,90.00,Cairo,New Cairo City,Al Rehab,90 m² ownership in the first phase at a bargain,2026-02-11 16:04:50+00:00
32458,"4,000,000.00",Apartment,55.00,Cairo,Madinaty,Privado,Studio 55m in B12 Madinaty | Facing Mosque & S...,2026-02-17 15:55:31+00:00
26188,"3,000,000.00",Villa,300.00,North Coast,Sidi Abdel Rahman,Hacienda White,"Standalone villa, prime location, Hacienda White",2026-02-26 22:19:24+00:00
27158,"3,000,000.00",Villa,500.00,North Coast,Sidi Abdel Rahman,Marassi,"Modern villa with sea view, first use, prime l...",2026-02-25 18:36:28+00:00
35466,"3,000,000.00",Villa,"1,000.00",North Coast,Sidi Abdel Rahman,Hacienda White,Standalone villa for rent fully finished,2026-02-12 16:30:57+00:00
24372,"2,400,000.00",Villa,220.00,North Coast,Ras Al Hekma,La vista Ras El Hikma,one story 220m in La Vista ras el hikma first row,2026-03-02 11:27:26+00:00
28875,"2,400,000.00",Villa,420.00,North Coast,Sidi Abdel Rahman,Seashell,villa for rent in seashell seasonal,2026-02-24 00:46:26+00:00
21445,"2,100,000.00",Villa,"1,500.00",North Coast,Sidi Abdel Rahman,Marassi,"A clean villa, first row from the sea, prime l...",2026-02-15 16:57:08+00:00
35476,"1,990,000.00",Villa,363.00,North Coast,Qesm Marsa Matrouh,Almaza Bay,Almaza Bay Standalone Villa Forth Row,2026-02-12 16:30:13+00:00
26186,"1,800,000.00",Chalet,220.00,North Coast,Sidi Abdel Rahman,Marassi,"Chalet, prime location, Marina Marassi, direct...",2026-02-26 22:20:59+00:00
20288,"1,705,000.00",Chalet,190.00,North Coast,Sidi Abdel Rahman,Marassi,Luxury First-Row Marina Apartment –Direct Sea ...,2026-02-21 18:08:41+00:00
21012,"1,650,000.00",Villa,400.00,North Coast,Qesm Marsa Matrouh,Almaza Bay,Villa for rent \Almaza bay selection full sea ...,2026-02-26 10:43:58+00:00
25966,"1,500,000.00",Villa,900.00,North Coast,Sidi Abdel Rahman,Hacienda Bay,Villa in a prime location Hacienda Bay ultra,2026-02-27 20:10:17+00:00
26183,"1,500,000.00",Chalet,220.00,North Coast,Sidi Abdel Rahman,Marassi,Chalet in a prime location in Marina Marassi,2026-02-26 22:22:36+00:00
35455,"1,500,000.00",Villa,363.00,North Coast,Sidi Abdel Rahman,Hacienda Bay,Hacienda Bay Villa Prime Location Fully Furnished,2026-02-12 16:32:01+00:00
37638,"1,350,000.00",Villa,350.00,North Coast,Al Alamein,Marina,"Villa furnished,AC/S,Frist Row the Sandy Lake",2026-02-10 11:15:31+00:00
29840,"1,300,000.00",Villa,600.00,North Coast,Al Alamein,Marina,Luxury Villa for Rent Marina7 First Row on the...,2026-02-23 03:19:17+00:00
28872,"1,250,000.00",Apartment,150.00,North Coast,Sidi Abdel Rahman,Marassi Bay,Chalet for rent in the North Coast – Marassi,2026-02-24 00:52:52+00:00
35464,"1,250,000.00",Villa,180.00,North Coast,Sidi Abdel Rahman,Hacienda White,Hacienda White Stand Alone Chalet 3 Bedrooms,2026-02-12 16:31:02+00:00
20246,"1,200,000.00",Apartment,140.00,North Coast,Qesm Ad Dabaah,Soul North Coast,2BR Marassi listed now on Zeezon,2026-02-22 12:19:35+00:00
21340,"1,200,000.00",Chalet,200.00,North Coast,Sidi Abdel Rahman,Hacienda White,Ground /Hacienda White/private pool/sea view,2026-02-17 12:51:38+00:00
34350,"1,200,000.00",Chalet,200.00,North Coast,Sidi Abdel Rahman,Hacienda White,chalet for rent with jacuzzi in hacienda white,2026-02-15 10:50:15+00:00
37462,"1,200,000.00",Villa,450.00,North Coast,Sidi Abdel Rahman,Seashell,"Prime Villa with Garden and Pool ,Super lux",2026-02-10 12:58:31+00:00
25965,"1,100,000.00",Villa,330.00,North Coast,Sidi Abdel Rahman,Hacienda Bay,"Villa VioGolf, prime location, ultra-super",2026-02-27 20:12:01+00:00
26185,"1,100,000.00",Chalet,195.00,North Coast,Sidi Abdel Rahman,Hacienda White,"Chalet, prime location, ultra super deluxe",2026-02-26 22:21:30+00:00
35463,"1,100,000.00",Chalet,400.00,North Coast,Sidi Abdel Rahman,Hacienda Red,Chalet for rent 3 bedrooms with private pool,2026-02-12 16:31:02+00:00
24428,"1,000,000.00",Whole Building,"1,271.00",Cairo,New Cairo City,El Lotus,Whole Building for rent in northern lotus 1271,2026-03-02 10:55:42+00:00
29645,"1,000,000.00",Villa,"1,000.00",North Coast,Sidi Abdel Rahman,Marassi,"Villa with a large garden, prime location, and...",2026-02-23 10:38:13+00:00
35465,"990,000.00",Chalet,184.00,North Coast,Qesm Marsa Matrouh,Almaza Bay,Almaza Bay Ground Chalet 2 Bedroom Fully Finished,2026-02-12 16:31:00+00:00
35467,"990,000.00",Chalet,400.00,North Coast,Sidi Abdel Rahman,Hacienda White,Ground Chalet With Pool For Rent At Hacienda W...,2026-02-12 16:30:57+00:00
35472,"990,000.00",Chalet,220.00,North Coast,Qesm Marsa Matrouh,Almaza Bay,Opportunity Almaza Bay Ground Chalet Furnished,2026-02-12 16:30:14+00:00
23100,"987,000.00",Penthouse,"1,000.00",Cairo,New Cairo City,El Katameya,Ultra Luxury Penthouse For rent in Katameya Dunes,2026-03-03 13:48:59+00:00
37502,"950,000.00",Apartment,190.00,Cairo,New Cairo City,The 5th Settlement,Furnished Apartment in Eastown with the best view,2026-02-10 12:24:35+00:00
20862,"900,000.00",Villa,"1,100.00",Cairo,Mokattam,Uptown Cairo,Great Location | Ready To Move In a Month,2026-03-04 15:23:17+00:00
27091,"900,000.00",Chalet,220.00,North Coast,Sidi Abdel Rahman,Hacienda White,"Ultra Super Lux Chalet, Prime Location",2026-02-25 21:16:10+00:00

In [ ]:
suspicious_high_rent = rent[
    (rent['price_egp'] > 2_000_000) &
    (rent['area_value'] < 1000) &
    (~rent['district'].isin(['Marassi', 'Ras Al Hekma','La vista Ras El Hikma','Marassi Bay','Seashell']))&
    (~(rent['town']=='Sidi Abdel Rahman'))
]

suspicious_high_rent[
    ['price_egp', 'property_type', 'area_value',
     'city', 'town', 'district', 'title']
]

,price_egp,property_type,area_value,city,town,district,title
20818,"160,000,000.00",Villa,357.00,Giza,6 October City,Cairo Alexandria Desert Road,Villa for Rent | New Giza Compound-Fully Finis...
21275,"125,000,000.00",Townhouse,380.00,Giza,6 October City,Al Wahat Road,Luxurious Corner Town House in Golf Extension
21807,"8,500,000.00",Apartment,67.00,Giza,6 October City,6 October Compounds,اقل سعر ستوديو ف ابراج ايون مراكز - مول العرب
22047,"5,300,000.00",Apartment,96.00,Cairo,Madinaty,Privado,Special finishing - Garden view - Next to Sout...
22297,"6,600,000.00",Apartment,132.00,Cairo,Madinaty,Privado,132m View Garden Seafront next to South Park
23113,"15,890,000.00",Apartment,162.00,Cairo,New Cairo City,The 5th Settlement,Luxury Apartment in Sodic Villette 5th Settlement
23155,"12,500,000.00",Apartment,200.00,Cairo,New Cairo City,The 5th Settlement,Apartment view Club House in Waterway The View
23211,"15,000,000.00",Duplex,245.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Premium finishing – Prime location
27617,"130,000,000.00",Townhouse,320.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,For Rent fully furnished townhouse at allegria
27915,"12,750,000.00",Apartment,198.00,Cairo,New Cairo City,The 5th Settlement,Apartment Bahary Fully Finished In Water Way
30895,"11,588,100.00",Apartment,118.00,Cairo,New Cairo City,Hyde Park,Apartment Under Market Price -With Installments
31340,"11,750,000.00",Apartment,163.00,Cairo,New Cairo City,The 5th Settlement,Exclusive APT161M view landscape Eastown main ...
31626,"16,000,000.00",Apartment,211.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Zed Towers View on Sheikh Zayed nice view
32458,"4,000,000.00",Apartment,55.00,Cairo,Madinaty,Privado,Studio 55m in B12 Madinaty | Facing Mosque & S...
32815,"37,000,000.00",Villa,360.00,Cairo,New Cairo City,The 5th Settlement,Very prime location Villa Ready to move In PK2
32827,"24,600,000.00",Townhouse,257.00,Cairo,New Cairo City,The 5th Settlement,Very prime location town house best price in PK2
33739,"185,000,000.00",Townhouse,260.00,Cairo,New Cairo City,South Investors Area,Town house for rent in la Terra furnished and ...
36358,"4,300,000.00",Apartment,90.00,Cairo,New Cairo City,Al Rehab,90 m² ownership in the first phase at a bargain
37398,"10,500,000.00",Apartment,140.00,Cairo,New Cairo City,The 5th Settlement,apartment with a stunning garden and Ac's Marssem
37860,"21,085,812.00",Twin House,290.00,Cairo,New Cairo City,Hyde Park,win villa for rent at Hyde Park Built up area 290
37865,"28,113,558.00",Villa,800.00,Cairo,New Cairo City,Hyde Park,Stand alone villa for rent at hyde park new comp
37982,"70,000,000.00",Apartment,122.00,Cairo,New Cairo City,The 5th Settlement,Apartment For Rent Fully Furnished Prime location
38152,"15,000,000.00",Villa,400.00,Cairo,New Cairo City,The 5th Settlement,Standalone Villa for Rent in Stone Park Compound
38232,"13,000,000.00",Apartment,200.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Opportunity to invest _ under market price
39114,"6,000,000.00",Apartment,235.00,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Ground-Floor Apartment with Front Garden

In [ ]:
suspicious_high_rent.shape

(25, 17)

In [ ]:
rent[
    (rent['price_egp'] > 2_000_000) &
    (rent['area_value'] < 1000) &
    (~rent['district'].isin(['Marassi', 'Ras Al Hekma','La vista Ras El Hikma','Marassi Bay','Seashell']))&
    (~(rent['town']=='Sidi Abdel Rahman'))
]

,property_type,title,price_egp,city,town,district,lat,lon,bedrooms,bathrooms,area_value,furnished,listing_level,listed_date,description,agent_id,broker_id
20818,Villa,Villa for Rent | New Giza Compound-Fully Finis...,"160,000,000.00",Giza,6 October City,Cairo Alexandria Desert Road,30.01,31.06,5,5,357.00,PARTLY,featured,2026-03-02 13:32:39+00:00,Villa for Rent | New Giza Compound | Fully Fin...,44424,606
21275,Townhouse,Luxurious Corner Town House in Golf Extension,"125,000,000.00",Giza,6 October City,Al Wahat Road,29.96,30.92,3,4,380.00,YES,featured,2026-02-20 12:38:21+00:00,Golf extension For rent Luxurious corner town ...,50088,5546
21807,Apartment,اقل سعر ستوديو ف ابراج ايون مراكز - مول العرب,"8,500,000.00",Giza,6 October City,6 October Compounds,30.01,30.97,studio,1,67.00,PARTLY,featured,2026-02-21 18:22:52+00:00,تفاصيل الاستوديو :-- - 67 متر - 1 غرفة نوم - 1...,72031,3137
22047,Apartment,Special finishing - Garden view - Next to Sout...,"5,300,000.00",Cairo,Madinaty,Privado,30.09,31.67,2,1,96.00,NO,standard,2026-03-04 19:34:07+00:00,96 sqm Apartment for Sale in Madinaty | Stunni...,53341,4364
22297,Apartment,132m View Garden Seafront next to South Park,"6,600,000.00",Cairo,Madinaty,Privado,30.09,31.67,3,2,132.00,NO,standard,2026-03-04 14:00:46+00:00,132 sqm Apartment for Sale in Madinaty | Stunn...,53341,4364
23113,Apartment,Luxury Apartment in Sodic Villette 5th Settlement,"15,890,000.00",Cairo,New Cairo City,The 5th Settlement,30.02,31.55,3,3,162.00,Unknown,standard,2026-03-03 13:32:00+00:00,Breathtaking Villa & Landscape Views – New Cai...,40373,4482
23155,Apartment,Apartment view Club House in Waterway The View,"12,500,000.00",Cairo,New Cairo City,The 5th Settlement,30.02,31.51,3,3,200.00,NO,standard,2026-03-03 13:05:46+00:00,Apartment for sale in Waterway The View-View c...,17178,1846
23211,Duplex,Premium finishing – Prime location,"15,000,000.00",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.07,30.96,3,3,245.00,NO,standard,2026-03-03 12:50:00+00:00,Duplex for Sale in Casa | Sheikh Zayed A disti...,67436,5932
27617,Townhouse,For Rent fully furnished townhouse at allegria,"130,000,000.00",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.07,30.96,3,4,320.00,YES,standard,2026-02-25 12:01:08+00:00,"Welcome to Allegria, one of SODIC’s most prest...",57721,3467
27915,Apartment,Apartment Bahary Fully Finished In Water Way,"12,750,000.00",Cairo,New Cairo City,The 5th Settlement,30.02,31.51,3,3,198.00,PARTLY,standard,2026-02-25 09:32:04+00:00,- *Location:*new cairo - Developer: Water Way ...,71369,6376
30895,Apartment,Apartment Under Market Price -With Installments,"11,588,100.00",Cairo,New Cairo City,Hyde Park,30.00,31.55,2,3,118.00,Unknown,standard,2026-02-21 13:58:00+00:00,Code HP195-BA1 Compound name : hyde park Unit ...,57352,4290
31340,Apartment,Exclusive APT161M view landscape Eastown main ...,"11,750,000.00",Cairo,New Cairo City,The 5th Settlement,30.01,31.52,2,3,163.00,Unknown,standard,2026-02-20 09:43:08+00:00,161 m² apartment with a view of the landscape ...,29218,2039
31626,Apartment,Zed Towers View on Sheikh Zayed nice view,"16,000,000.00",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.05,31.00,3,3,211.00,YES,standard,2026-02-26 19:23:57+00:00,Zed Towers - Stunning View on Sheikh Zayed 211...,43890,2098
32458,Apartment,Studio 55m in B12 Madinaty | Facing Mosque & S...,"4,000,000.00",Cairo,Madinaty,Privado,30.09,31.67,1,1,55.00,YES,standard,2026-02-17 15:55:31+00:00,Studio for Sale in Madinaty – B12 A great oppo...,68789,1709
32815,Villa,Very prime location Villa Ready to move In PK2,"37,000,000.00",Cairo,New Cairo City,The 5th Settlement,30.04,31.54,4,4,360.00,Unknown,standard,2026-02-17 12:08:11+00:00,villa for sale in pk2 prime location BUA : 360...,69044,2410
32827,Townhouse,Very prime location town house best price in PK2,"24,600,000.00",Cairo,New Cairo City,The 5th Settlement,30.04,31.54,4,4,257.00,NO,standard,2026-02-17 11:57:55+00:00,town house for Sale in Palm hills katameya com...,69044,2410
33739,Townhouse,Town house for rent in la Terra furnished and ...,"185,000,000.00",Cairo,New Cairo City,South Investors Area,30.01,31.50,4,5,260.00,YES,standard,2026-02-16 07:56:37+00:00,Villa twon house for rent in latera With furni...,70411,6359
36358,Apartment,90 m² ownership in the first phase at a bargain,"4,300,000.00",Cairo,New Cairo City,Al Rehab,30.06,31.51,2,1,90.00,NO,standard,2026-02-11 16:04:50+00:00,90 m² for sale in the first phase at a bargain...,49258,5460
37398,Apartment,apartment with a stunning garden and Ac's Marssem,"10,500,000.00",Cairo,New Cairo City,The 5th Settlement,30.05,31.54,3,2,140.00,PARTLY,standard,2026-02-10 13:27:38+00:00,A distinctive apartment with a stunning garden...,34457,3767
37860,Twin House,win villa for rent at Hyde Park Built up area 290,"21,085,812.00",Cairo,New Cairo City,Hyde Park,30.00,31.55,5,5,290.00,PARTLY,standard,2026-02-09 21:48:14+00:00,Twin villa for rent at Hyde Park Built up area...,33039,3815
37865,Villa,Stand alone villa for rent at hyde park new comp,"28,113,558.00",Cairo,New Cairo City,Hyde Park,30.00,31.55,4,5,800.00,PARTLY,standard,2026-02-09 21:24:46+00:00,Stand alone villa for rent at hyde park new co...,33039,3815
37982,Apartment,Apartment For Rent Fully Furnished Prime location,"70,000,000.00",Cairo,New Cairo City,The 5th Settlement,30.03,31.54,2,2,122.00,YES,standard,2026-02-09 16:47:00+00:00,Compound lake view residence Apartment 122m + ...,39437,741
38152,Villa,Standalone Villa for Rent in Stone Park Compound,"15,000,000.00",Cairo,New Cairo City,The 5th Settlement,29.99,31.39,3,3,400.00,YES,standard,2026-02-09 14:11:09+00:00,Standalone Villa for Rent in Stone Park Compou...,66876,66
38232,Apartment,Opportunity to invest _ under market price,"13,000,000.00",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.04,30.99,3,3,200.00,Unknown,standard,2026-02-09 13:35:28+00:00,For sale apartment in Courtyard sodic Courtyar...,56003,5932
39114,Apartment,Ground-Floor Apartment with Front Garden,"6,000,000.00",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,30.04,30.99,3,2,235.00,Unknown,standard,2026-02-08 14:57:36+00:00,A prime apartment for sale in Zayed Heights Co...,71544,266

In [ ]:
rent = rent.drop(index=suspicious_high_rent.index).copy()

In [ ]:
# sell.to_csv('Sell(super cleaned).csv', index=False)
# rent.to_csv('Rent(super cleaned).csv', index=False)